
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model DocumentType
 * 
 */
export type DocumentType = Prisma.DocumentTypeModel
/**
 * Model NaturalPersonDetail
 * 
 */
export type NaturalPersonDetail = Prisma.NaturalPersonDetailModel
/**
 * Model LegalPersonDetail
 * 
 */
export type LegalPersonDetail = Prisma.LegalPersonDetailModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model Permission
 * 
 */
export type Permission = Prisma.PermissionModel
/**
 * Model UserRole
 * 
 */
export type UserRole = Prisma.UserRoleModel
/**
 * Model RolePermission
 * 
 */
export type RolePermission = Prisma.RolePermissionModel
/**
 * Model UsersRaw
 * 
 */
export type UsersRaw = Prisma.UsersRawModel
/**
 * Model Property
 * 
 */
export type Property = Prisma.PropertyModel
/**
 * Model Address
 * 
 */
export type Address = Prisma.AddressModel
/**
 * Model Listing
 * 
 */
export type Listing = Prisma.ListingModel
/**
 * Model Photo
 * 
 */
export type Photo = Prisma.PhotoModel
/**
 * Model AdditionalFeature
 * 
 */
export type AdditionalFeature = Prisma.AdditionalFeatureModel
/**
 * Model PropertyAdditionalFeature
 * 
 */
export type PropertyAdditionalFeature = Prisma.PropertyAdditionalFeatureModel
/**
 * Model PropertyType
 * 
 */
export type PropertyType = Prisma.PropertyTypeModel
/**
 * Model Department
 * 
 */
export type Department = Prisma.DepartmentModel
/**
 * Model City
 * 
 */
export type City = Prisma.CityModel
/**
 * Model PropertyListingsRaw
 * 
 */
export type PropertyListingsRaw = Prisma.PropertyListingsRawModel
/**
 * Model LandlordPortfolio
 * 
 */
export type LandlordPortfolio = Prisma.LandlordPortfolioModel
/**
 * Model PortfolioUnit
 * 
 */
export type PortfolioUnit = Prisma.PortfolioUnitModel
/**
 * Model Lease
 * 
 */
export type Lease = Prisma.LeaseModel
/**
 * Model PortfolioRaw
 * 
 */
export type PortfolioRaw = Prisma.PortfolioRawModel
/**
 * Model LeaseStatus
 * 
 */
export type LeaseStatus = Prisma.LeaseStatusModel
/**
 * Model LeaseStatusHistory
 * 
 */
export type LeaseStatusHistory = Prisma.LeaseStatusHistoryModel
/**
 * Model LeaseCurrentStatus
 * 
 */
export type LeaseCurrentStatus = Prisma.LeaseCurrentStatusModel
/**
 * Model ListingStatus
 * 
 */
export type ListingStatus = Prisma.ListingStatusModel
/**
 * Model ListingStatusHistory
 * 
 */
export type ListingStatusHistory = Prisma.ListingStatusHistoryModel
/**
 * Model ListingCurrentStatus
 * 
 */
export type ListingCurrentStatus = Prisma.ListingCurrentStatusModel
/**
 * Model TrackingRaw
 * 
 */
export type TrackingRaw = Prisma.TrackingRawModel
/**
 * Model ScheduledPayment
 * 
 */
export type ScheduledPayment = Prisma.ScheduledPaymentModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model PaymentStatus
 * 
 */
export type PaymentStatus = Prisma.PaymentStatusModel
/**
 * Model PaymentLog
 * 
 */
export type PaymentLog = Prisma.PaymentLogModel
/**
 * Model PaymentsRaw
 * 
 */
export type PaymentsRaw = Prisma.PaymentsRawModel
/**
 * Model AggregatedPaymentReport
 * 
 */
export type AggregatedPaymentReport = Prisma.AggregatedPaymentReportModel
/**
 * Model IndividualPaymentReport
 * 
 */
export type IndividualPaymentReport = Prisma.IndividualPaymentReportModel
/**
 * Model AccountingRaw
 * 
 */
export type AccountingRaw = Prisma.AccountingRawModel
/**
 * Model NotificationType
 * 
 */
export type NotificationType = Prisma.NotificationTypeModel
/**
 * Model InAppNotification
 * 
 */
export type InAppNotification = Prisma.InAppNotificationModel
/**
 * Model NotificationPreference
 * 
 */
export type NotificationPreference = Prisma.NotificationPreferenceModel
/**
 * Model NotificationsRaw
 * 
 */
export type NotificationsRaw = Prisma.NotificationsRawModel
/**
 * Model ContractStatus
 * 
 */
export type ContractStatus = Prisma.ContractStatusModel
/**
 * Model Contract
 * 
 */
export type Contract = Prisma.ContractModel
/**
 * Model ContractParty
 * 
 */
export type ContractParty = Prisma.ContractPartyModel
/**
 * Model FileType
 * 
 */
export type FileType = Prisma.FileTypeModel
/**
 * Model FileStatus
 * 
 */
export type FileStatus = Prisma.FileStatusModel
/**
 * Model File
 * 
 */
export type File = Prisma.FileModel
/**
 * Model SigningStatus
 * 
 */
export type SigningStatus = Prisma.SigningStatusModel
/**
 * Model Signing
 * 
 */
export type Signing = Prisma.SigningModel
/**
 * Model SigningLog
 * 
 */
export type SigningLog = Prisma.SigningLogModel
/**
 * Model ContractsRaw
 * 
 */
export type ContractsRaw = Prisma.ContractsRawModel
