
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FileStatus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FileStatus
 * 
 */
export type FileStatusModel = runtime.Types.Result.DefaultSelection<Prisma.$FileStatusPayload>

export type AggregateFileStatus = {
  _count: FileStatusCountAggregateOutputType | null
  _min: FileStatusMinAggregateOutputType | null
  _max: FileStatusMaxAggregateOutputType | null
}

export type FileStatusMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  deleted_at: Date | null
}

export type FileStatusMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  deleted_at: Date | null
}

export type FileStatusCountAggregateOutputType = {
  id: number
  name: number
  description: number
  deleted_at: number
  _all: number
}


export type FileStatusMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  deleted_at?: true
}

export type FileStatusMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  deleted_at?: true
}

export type FileStatusCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  deleted_at?: true
  _all?: true
}

export type FileStatusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileStatus to aggregate.
   */
  where?: Prisma.FileStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileStatuses to fetch.
   */
  orderBy?: Prisma.FileStatusOrderByWithRelationInput | Prisma.FileStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FileStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FileStatuses
  **/
  _count?: true | FileStatusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FileStatusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FileStatusMaxAggregateInputType
}

export type GetFileStatusAggregateType<T extends FileStatusAggregateArgs> = {
      [P in keyof T & keyof AggregateFileStatus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFileStatus[P]>
    : Prisma.GetScalarType<T[P], AggregateFileStatus[P]>
}




export type FileStatusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileStatusWhereInput
  orderBy?: Prisma.FileStatusOrderByWithAggregationInput | Prisma.FileStatusOrderByWithAggregationInput[]
  by: Prisma.FileStatusScalarFieldEnum[] | Prisma.FileStatusScalarFieldEnum
  having?: Prisma.FileStatusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FileStatusCountAggregateInputType | true
  _min?: FileStatusMinAggregateInputType
  _max?: FileStatusMaxAggregateInputType
}

export type FileStatusGroupByOutputType = {
  id: string
  name: string
  description: string | null
  deleted_at: Date | null
  _count: FileStatusCountAggregateOutputType | null
  _min: FileStatusMinAggregateOutputType | null
  _max: FileStatusMaxAggregateOutputType | null
}

export type GetFileStatusGroupByPayload<T extends FileStatusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FileStatusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FileStatusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FileStatusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FileStatusGroupByOutputType[P]>
      }
    >
  >



export type FileStatusWhereInput = {
  AND?: Prisma.FileStatusWhereInput | Prisma.FileStatusWhereInput[]
  OR?: Prisma.FileStatusWhereInput[]
  NOT?: Prisma.FileStatusWhereInput | Prisma.FileStatusWhereInput[]
  id?: Prisma.StringFilter<"FileStatus"> | string
  name?: Prisma.StringFilter<"FileStatus"> | string
  description?: Prisma.StringNullableFilter<"FileStatus"> | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"FileStatus"> | Date | string | null
  files?: Prisma.FileListRelationFilter
}

export type FileStatusOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  files?: Prisma.FileOrderByRelationAggregateInput
}

export type FileStatusWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.FileStatusWhereInput | Prisma.FileStatusWhereInput[]
  OR?: Prisma.FileStatusWhereInput[]
  NOT?: Prisma.FileStatusWhereInput | Prisma.FileStatusWhereInput[]
  description?: Prisma.StringNullableFilter<"FileStatus"> | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"FileStatus"> | Date | string | null
  files?: Prisma.FileListRelationFilter
}, "id" | "name">

export type FileStatusOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.FileStatusCountOrderByAggregateInput
  _max?: Prisma.FileStatusMaxOrderByAggregateInput
  _min?: Prisma.FileStatusMinOrderByAggregateInput
}

export type FileStatusScalarWhereWithAggregatesInput = {
  AND?: Prisma.FileStatusScalarWhereWithAggregatesInput | Prisma.FileStatusScalarWhereWithAggregatesInput[]
  OR?: Prisma.FileStatusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FileStatusScalarWhereWithAggregatesInput | Prisma.FileStatusScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FileStatus"> | string
  name?: Prisma.StringWithAggregatesFilter<"FileStatus"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"FileStatus"> | string | null
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"FileStatus"> | Date | string | null
}

export type FileStatusCreateInput = {
  id?: string
  name: string
  description?: string | null
  deleted_at?: Date | string | null
  files?: Prisma.FileCreateNestedManyWithoutFile_statusInput
}

export type FileStatusUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  deleted_at?: Date | string | null
  files?: Prisma.FileUncheckedCreateNestedManyWithoutFile_statusInput
}

export type FileStatusUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  files?: Prisma.FileUpdateManyWithoutFile_statusNestedInput
}

export type FileStatusUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  files?: Prisma.FileUncheckedUpdateManyWithoutFile_statusNestedInput
}

export type FileStatusCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  deleted_at?: Date | string | null
}

export type FileStatusUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FileStatusUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FileStatusCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type FileStatusMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type FileStatusMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type FileStatusScalarRelationFilter = {
  is?: Prisma.FileStatusWhereInput
  isNot?: Prisma.FileStatusWhereInput
}

export type FileStatusCreateNestedOneWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.FileStatusCreateWithoutFilesInput, Prisma.FileStatusUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.FileStatusCreateOrConnectWithoutFilesInput
  connect?: Prisma.FileStatusWhereUniqueInput
}

export type FileStatusUpdateOneRequiredWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.FileStatusCreateWithoutFilesInput, Prisma.FileStatusUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.FileStatusCreateOrConnectWithoutFilesInput
  upsert?: Prisma.FileStatusUpsertWithoutFilesInput
  connect?: Prisma.FileStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FileStatusUpdateToOneWithWhereWithoutFilesInput, Prisma.FileStatusUpdateWithoutFilesInput>, Prisma.FileStatusUncheckedUpdateWithoutFilesInput>
}

export type FileStatusCreateWithoutFilesInput = {
  id?: string
  name: string
  description?: string | null
  deleted_at?: Date | string | null
}

export type FileStatusUncheckedCreateWithoutFilesInput = {
  id?: string
  name: string
  description?: string | null
  deleted_at?: Date | string | null
}

export type FileStatusCreateOrConnectWithoutFilesInput = {
  where: Prisma.FileStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.FileStatusCreateWithoutFilesInput, Prisma.FileStatusUncheckedCreateWithoutFilesInput>
}

export type FileStatusUpsertWithoutFilesInput = {
  update: Prisma.XOR<Prisma.FileStatusUpdateWithoutFilesInput, Prisma.FileStatusUncheckedUpdateWithoutFilesInput>
  create: Prisma.XOR<Prisma.FileStatusCreateWithoutFilesInput, Prisma.FileStatusUncheckedCreateWithoutFilesInput>
  where?: Prisma.FileStatusWhereInput
}

export type FileStatusUpdateToOneWithWhereWithoutFilesInput = {
  where?: Prisma.FileStatusWhereInput
  data: Prisma.XOR<Prisma.FileStatusUpdateWithoutFilesInput, Prisma.FileStatusUncheckedUpdateWithoutFilesInput>
}

export type FileStatusUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FileStatusUncheckedUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type FileStatusCountOutputType
 */

export type FileStatusCountOutputType = {
  files: number
}

export type FileStatusCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | FileStatusCountOutputTypeCountFilesArgs
}

/**
 * FileStatusCountOutputType without action
 */
export type FileStatusCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatusCountOutputType
   */
  select?: Prisma.FileStatusCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FileStatusCountOutputType without action
 */
export type FileStatusCountOutputTypeCountFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileWhereInput
}


export type FileStatusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  deleted_at?: boolean
  files?: boolean | Prisma.FileStatus$filesArgs<ExtArgs>
  _count?: boolean | Prisma.FileStatusCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileStatus"]>

export type FileStatusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  deleted_at?: boolean
}, ExtArgs["result"]["fileStatus"]>

export type FileStatusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  deleted_at?: boolean
}, ExtArgs["result"]["fileStatus"]>

export type FileStatusSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  deleted_at?: boolean
}

export type FileStatusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "deleted_at", ExtArgs["result"]["fileStatus"]>
export type FileStatusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | Prisma.FileStatus$filesArgs<ExtArgs>
  _count?: boolean | Prisma.FileStatusCountOutputTypeDefaultArgs<ExtArgs>
}
export type FileStatusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FileStatusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FileStatusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FileStatus"
  objects: {
    files: Prisma.$FilePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    deleted_at: Date | null
  }, ExtArgs["result"]["fileStatus"]>
  composites: {}
}

export type FileStatusGetPayload<S extends boolean | null | undefined | FileStatusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FileStatusPayload, S>

export type FileStatusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FileStatusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FileStatusCountAggregateInputType | true
  }

export interface FileStatusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FileStatus'], meta: { name: 'FileStatus' } }
  /**
   * Find zero or one FileStatus that matches the filter.
   * @param {FileStatusFindUniqueArgs} args - Arguments to find a FileStatus
   * @example
   * // Get one FileStatus
   * const fileStatus = await prisma.fileStatus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FileStatusFindUniqueArgs>(args: Prisma.SelectSubset<T, FileStatusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FileStatusClient<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FileStatus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FileStatusFindUniqueOrThrowArgs} args - Arguments to find a FileStatus
   * @example
   * // Get one FileStatus
   * const fileStatus = await prisma.fileStatus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FileStatusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FileStatusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileStatusClient<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileStatus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileStatusFindFirstArgs} args - Arguments to find a FileStatus
   * @example
   * // Get one FileStatus
   * const fileStatus = await prisma.fileStatus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FileStatusFindFirstArgs>(args?: Prisma.SelectSubset<T, FileStatusFindFirstArgs<ExtArgs>>): Prisma.Prisma__FileStatusClient<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileStatus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileStatusFindFirstOrThrowArgs} args - Arguments to find a FileStatus
   * @example
   * // Get one FileStatus
   * const fileStatus = await prisma.fileStatus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FileStatusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FileStatusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileStatusClient<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FileStatuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileStatusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FileStatuses
   * const fileStatuses = await prisma.fileStatus.findMany()
   * 
   * // Get first 10 FileStatuses
   * const fileStatuses = await prisma.fileStatus.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fileStatusWithIdOnly = await prisma.fileStatus.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FileStatusFindManyArgs>(args?: Prisma.SelectSubset<T, FileStatusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FileStatus.
   * @param {FileStatusCreateArgs} args - Arguments to create a FileStatus.
   * @example
   * // Create one FileStatus
   * const FileStatus = await prisma.fileStatus.create({
   *   data: {
   *     // ... data to create a FileStatus
   *   }
   * })
   * 
   */
  create<T extends FileStatusCreateArgs>(args: Prisma.SelectSubset<T, FileStatusCreateArgs<ExtArgs>>): Prisma.Prisma__FileStatusClient<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FileStatuses.
   * @param {FileStatusCreateManyArgs} args - Arguments to create many FileStatuses.
   * @example
   * // Create many FileStatuses
   * const fileStatus = await prisma.fileStatus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FileStatusCreateManyArgs>(args?: Prisma.SelectSubset<T, FileStatusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FileStatuses and returns the data saved in the database.
   * @param {FileStatusCreateManyAndReturnArgs} args - Arguments to create many FileStatuses.
   * @example
   * // Create many FileStatuses
   * const fileStatus = await prisma.fileStatus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FileStatuses and only return the `id`
   * const fileStatusWithIdOnly = await prisma.fileStatus.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FileStatusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FileStatusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FileStatus.
   * @param {FileStatusDeleteArgs} args - Arguments to delete one FileStatus.
   * @example
   * // Delete one FileStatus
   * const FileStatus = await prisma.fileStatus.delete({
   *   where: {
   *     // ... filter to delete one FileStatus
   *   }
   * })
   * 
   */
  delete<T extends FileStatusDeleteArgs>(args: Prisma.SelectSubset<T, FileStatusDeleteArgs<ExtArgs>>): Prisma.Prisma__FileStatusClient<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FileStatus.
   * @param {FileStatusUpdateArgs} args - Arguments to update one FileStatus.
   * @example
   * // Update one FileStatus
   * const fileStatus = await prisma.fileStatus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FileStatusUpdateArgs>(args: Prisma.SelectSubset<T, FileStatusUpdateArgs<ExtArgs>>): Prisma.Prisma__FileStatusClient<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FileStatuses.
   * @param {FileStatusDeleteManyArgs} args - Arguments to filter FileStatuses to delete.
   * @example
   * // Delete a few FileStatuses
   * const { count } = await prisma.fileStatus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FileStatusDeleteManyArgs>(args?: Prisma.SelectSubset<T, FileStatusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FileStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileStatusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FileStatuses
   * const fileStatus = await prisma.fileStatus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FileStatusUpdateManyArgs>(args: Prisma.SelectSubset<T, FileStatusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FileStatuses and returns the data updated in the database.
   * @param {FileStatusUpdateManyAndReturnArgs} args - Arguments to update many FileStatuses.
   * @example
   * // Update many FileStatuses
   * const fileStatus = await prisma.fileStatus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FileStatuses and only return the `id`
   * const fileStatusWithIdOnly = await prisma.fileStatus.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FileStatusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FileStatusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FileStatus.
   * @param {FileStatusUpsertArgs} args - Arguments to update or create a FileStatus.
   * @example
   * // Update or create a FileStatus
   * const fileStatus = await prisma.fileStatus.upsert({
   *   create: {
   *     // ... data to create a FileStatus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FileStatus we want to update
   *   }
   * })
   */
  upsert<T extends FileStatusUpsertArgs>(args: Prisma.SelectSubset<T, FileStatusUpsertArgs<ExtArgs>>): Prisma.Prisma__FileStatusClient<runtime.Types.Result.GetResult<Prisma.$FileStatusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FileStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileStatusCountArgs} args - Arguments to filter FileStatuses to count.
   * @example
   * // Count the number of FileStatuses
   * const count = await prisma.fileStatus.count({
   *   where: {
   *     // ... the filter for the FileStatuses we want to count
   *   }
   * })
  **/
  count<T extends FileStatusCountArgs>(
    args?: Prisma.Subset<T, FileStatusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FileStatusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FileStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileStatusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FileStatusAggregateArgs>(args: Prisma.Subset<T, FileStatusAggregateArgs>): Prisma.PrismaPromise<GetFileStatusAggregateType<T>>

  /**
   * Group by FileStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileStatusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FileStatusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FileStatusGroupByArgs['orderBy'] }
      : { orderBy?: FileStatusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FileStatusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFileStatusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FileStatus model
 */
readonly fields: FileStatusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FileStatus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FileStatusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  files<T extends Prisma.FileStatus$filesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FileStatus$filesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FileStatus model
 */
export interface FileStatusFieldRefs {
  readonly id: Prisma.FieldRef<"FileStatus", 'String'>
  readonly name: Prisma.FieldRef<"FileStatus", 'String'>
  readonly description: Prisma.FieldRef<"FileStatus", 'String'>
  readonly deleted_at: Prisma.FieldRef<"FileStatus", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FileStatus findUnique
 */
export type FileStatusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
  /**
   * Filter, which FileStatus to fetch.
   */
  where: Prisma.FileStatusWhereUniqueInput
}

/**
 * FileStatus findUniqueOrThrow
 */
export type FileStatusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
  /**
   * Filter, which FileStatus to fetch.
   */
  where: Prisma.FileStatusWhereUniqueInput
}

/**
 * FileStatus findFirst
 */
export type FileStatusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
  /**
   * Filter, which FileStatus to fetch.
   */
  where?: Prisma.FileStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileStatuses to fetch.
   */
  orderBy?: Prisma.FileStatusOrderByWithRelationInput | Prisma.FileStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileStatuses.
   */
  cursor?: Prisma.FileStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileStatuses.
   */
  distinct?: Prisma.FileStatusScalarFieldEnum | Prisma.FileStatusScalarFieldEnum[]
}

/**
 * FileStatus findFirstOrThrow
 */
export type FileStatusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
  /**
   * Filter, which FileStatus to fetch.
   */
  where?: Prisma.FileStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileStatuses to fetch.
   */
  orderBy?: Prisma.FileStatusOrderByWithRelationInput | Prisma.FileStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileStatuses.
   */
  cursor?: Prisma.FileStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileStatuses.
   */
  distinct?: Prisma.FileStatusScalarFieldEnum | Prisma.FileStatusScalarFieldEnum[]
}

/**
 * FileStatus findMany
 */
export type FileStatusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
  /**
   * Filter, which FileStatuses to fetch.
   */
  where?: Prisma.FileStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileStatuses to fetch.
   */
  orderBy?: Prisma.FileStatusOrderByWithRelationInput | Prisma.FileStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FileStatuses.
   */
  cursor?: Prisma.FileStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileStatuses.
   */
  distinct?: Prisma.FileStatusScalarFieldEnum | Prisma.FileStatusScalarFieldEnum[]
}

/**
 * FileStatus create
 */
export type FileStatusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
  /**
   * The data needed to create a FileStatus.
   */
  data: Prisma.XOR<Prisma.FileStatusCreateInput, Prisma.FileStatusUncheckedCreateInput>
}

/**
 * FileStatus createMany
 */
export type FileStatusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FileStatuses.
   */
  data: Prisma.FileStatusCreateManyInput | Prisma.FileStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FileStatus createManyAndReturn
 */
export type FileStatusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * The data used to create many FileStatuses.
   */
  data: Prisma.FileStatusCreateManyInput | Prisma.FileStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FileStatus update
 */
export type FileStatusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
  /**
   * The data needed to update a FileStatus.
   */
  data: Prisma.XOR<Prisma.FileStatusUpdateInput, Prisma.FileStatusUncheckedUpdateInput>
  /**
   * Choose, which FileStatus to update.
   */
  where: Prisma.FileStatusWhereUniqueInput
}

/**
 * FileStatus updateMany
 */
export type FileStatusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FileStatuses.
   */
  data: Prisma.XOR<Prisma.FileStatusUpdateManyMutationInput, Prisma.FileStatusUncheckedUpdateManyInput>
  /**
   * Filter which FileStatuses to update
   */
  where?: Prisma.FileStatusWhereInput
  /**
   * Limit how many FileStatuses to update.
   */
  limit?: number
}

/**
 * FileStatus updateManyAndReturn
 */
export type FileStatusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * The data used to update FileStatuses.
   */
  data: Prisma.XOR<Prisma.FileStatusUpdateManyMutationInput, Prisma.FileStatusUncheckedUpdateManyInput>
  /**
   * Filter which FileStatuses to update
   */
  where?: Prisma.FileStatusWhereInput
  /**
   * Limit how many FileStatuses to update.
   */
  limit?: number
}

/**
 * FileStatus upsert
 */
export type FileStatusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
  /**
   * The filter to search for the FileStatus to update in case it exists.
   */
  where: Prisma.FileStatusWhereUniqueInput
  /**
   * In case the FileStatus found by the `where` argument doesn't exist, create a new FileStatus with this data.
   */
  create: Prisma.XOR<Prisma.FileStatusCreateInput, Prisma.FileStatusUncheckedCreateInput>
  /**
   * In case the FileStatus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FileStatusUpdateInput, Prisma.FileStatusUncheckedUpdateInput>
}

/**
 * FileStatus delete
 */
export type FileStatusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
  /**
   * Filter which FileStatus to delete.
   */
  where: Prisma.FileStatusWhereUniqueInput
}

/**
 * FileStatus deleteMany
 */
export type FileStatusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileStatuses to delete
   */
  where?: Prisma.FileStatusWhereInput
  /**
   * Limit how many FileStatuses to delete.
   */
  limit?: number
}

/**
 * FileStatus.files
 */
export type FileStatus$filesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  where?: Prisma.FileWhereInput
  orderBy?: Prisma.FileOrderByWithRelationInput | Prisma.FileOrderByWithRelationInput[]
  cursor?: Prisma.FileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FileScalarFieldEnum | Prisma.FileScalarFieldEnum[]
}

/**
 * FileStatus without action
 */
export type FileStatusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileStatus
   */
  select?: Prisma.FileStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileStatus
   */
  omit?: Prisma.FileStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileStatusInclude<ExtArgs> | null
}
