
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LeaseCurrentStatus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model LeaseCurrentStatus
 * 
 */
export type LeaseCurrentStatusModel = runtime.Types.Result.DefaultSelection<Prisma.$LeaseCurrentStatusPayload>

export type AggregateLeaseCurrentStatus = {
  _count: LeaseCurrentStatusCountAggregateOutputType | null
  _min: LeaseCurrentStatusMinAggregateOutputType | null
  _max: LeaseCurrentStatusMaxAggregateOutputType | null
}

export type LeaseCurrentStatusMinAggregateOutputType = {
  lease_id: string | null
  lease_status_history_id: string | null
  lease_status_id: string | null
  deleted_at: Date | null
}

export type LeaseCurrentStatusMaxAggregateOutputType = {
  lease_id: string | null
  lease_status_history_id: string | null
  lease_status_id: string | null
  deleted_at: Date | null
}

export type LeaseCurrentStatusCountAggregateOutputType = {
  lease_id: number
  lease_status_history_id: number
  lease_status_id: number
  deleted_at: number
  _all: number
}


export type LeaseCurrentStatusMinAggregateInputType = {
  lease_id?: true
  lease_status_history_id?: true
  lease_status_id?: true
  deleted_at?: true
}

export type LeaseCurrentStatusMaxAggregateInputType = {
  lease_id?: true
  lease_status_history_id?: true
  lease_status_id?: true
  deleted_at?: true
}

export type LeaseCurrentStatusCountAggregateInputType = {
  lease_id?: true
  lease_status_history_id?: true
  lease_status_id?: true
  deleted_at?: true
  _all?: true
}

export type LeaseCurrentStatusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LeaseCurrentStatus to aggregate.
   */
  where?: Prisma.LeaseCurrentStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LeaseCurrentStatuses to fetch.
   */
  orderBy?: Prisma.LeaseCurrentStatusOrderByWithRelationInput | Prisma.LeaseCurrentStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LeaseCurrentStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LeaseCurrentStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LeaseCurrentStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LeaseCurrentStatuses
  **/
  _count?: true | LeaseCurrentStatusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LeaseCurrentStatusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LeaseCurrentStatusMaxAggregateInputType
}

export type GetLeaseCurrentStatusAggregateType<T extends LeaseCurrentStatusAggregateArgs> = {
      [P in keyof T & keyof AggregateLeaseCurrentStatus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLeaseCurrentStatus[P]>
    : Prisma.GetScalarType<T[P], AggregateLeaseCurrentStatus[P]>
}




export type LeaseCurrentStatusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeaseCurrentStatusWhereInput
  orderBy?: Prisma.LeaseCurrentStatusOrderByWithAggregationInput | Prisma.LeaseCurrentStatusOrderByWithAggregationInput[]
  by: Prisma.LeaseCurrentStatusScalarFieldEnum[] | Prisma.LeaseCurrentStatusScalarFieldEnum
  having?: Prisma.LeaseCurrentStatusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LeaseCurrentStatusCountAggregateInputType | true
  _min?: LeaseCurrentStatusMinAggregateInputType
  _max?: LeaseCurrentStatusMaxAggregateInputType
}

export type LeaseCurrentStatusGroupByOutputType = {
  lease_id: string
  lease_status_history_id: string
  lease_status_id: string
  deleted_at: Date | null
  _count: LeaseCurrentStatusCountAggregateOutputType | null
  _min: LeaseCurrentStatusMinAggregateOutputType | null
  _max: LeaseCurrentStatusMaxAggregateOutputType | null
}

export type GetLeaseCurrentStatusGroupByPayload<T extends LeaseCurrentStatusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LeaseCurrentStatusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LeaseCurrentStatusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LeaseCurrentStatusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LeaseCurrentStatusGroupByOutputType[P]>
      }
    >
  >



export type LeaseCurrentStatusWhereInput = {
  AND?: Prisma.LeaseCurrentStatusWhereInput | Prisma.LeaseCurrentStatusWhereInput[]
  OR?: Prisma.LeaseCurrentStatusWhereInput[]
  NOT?: Prisma.LeaseCurrentStatusWhereInput | Prisma.LeaseCurrentStatusWhereInput[]
  lease_id?: Prisma.StringFilter<"LeaseCurrentStatus"> | string
  lease_status_history_id?: Prisma.StringFilter<"LeaseCurrentStatus"> | string
  lease_status_id?: Prisma.StringFilter<"LeaseCurrentStatus"> | string
  deleted_at?: Prisma.DateTimeNullableFilter<"LeaseCurrentStatus"> | Date | string | null
  history?: Prisma.XOR<Prisma.LeaseStatusHistoryScalarRelationFilter, Prisma.LeaseStatusHistoryWhereInput>
  status?: Prisma.XOR<Prisma.LeaseStatusScalarRelationFilter, Prisma.LeaseStatusWhereInput>
}

export type LeaseCurrentStatusOrderByWithRelationInput = {
  lease_id?: Prisma.SortOrder
  lease_status_history_id?: Prisma.SortOrder
  lease_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  history?: Prisma.LeaseStatusHistoryOrderByWithRelationInput
  status?: Prisma.LeaseStatusOrderByWithRelationInput
}

export type LeaseCurrentStatusWhereUniqueInput = Prisma.AtLeast<{
  lease_id?: string
  lease_status_history_id?: string
  AND?: Prisma.LeaseCurrentStatusWhereInput | Prisma.LeaseCurrentStatusWhereInput[]
  OR?: Prisma.LeaseCurrentStatusWhereInput[]
  NOT?: Prisma.LeaseCurrentStatusWhereInput | Prisma.LeaseCurrentStatusWhereInput[]
  lease_status_id?: Prisma.StringFilter<"LeaseCurrentStatus"> | string
  deleted_at?: Prisma.DateTimeNullableFilter<"LeaseCurrentStatus"> | Date | string | null
  history?: Prisma.XOR<Prisma.LeaseStatusHistoryScalarRelationFilter, Prisma.LeaseStatusHistoryWhereInput>
  status?: Prisma.XOR<Prisma.LeaseStatusScalarRelationFilter, Prisma.LeaseStatusWhereInput>
}, "lease_id" | "lease_status_history_id">

export type LeaseCurrentStatusOrderByWithAggregationInput = {
  lease_id?: Prisma.SortOrder
  lease_status_history_id?: Prisma.SortOrder
  lease_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.LeaseCurrentStatusCountOrderByAggregateInput
  _max?: Prisma.LeaseCurrentStatusMaxOrderByAggregateInput
  _min?: Prisma.LeaseCurrentStatusMinOrderByAggregateInput
}

export type LeaseCurrentStatusScalarWhereWithAggregatesInput = {
  AND?: Prisma.LeaseCurrentStatusScalarWhereWithAggregatesInput | Prisma.LeaseCurrentStatusScalarWhereWithAggregatesInput[]
  OR?: Prisma.LeaseCurrentStatusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LeaseCurrentStatusScalarWhereWithAggregatesInput | Prisma.LeaseCurrentStatusScalarWhereWithAggregatesInput[]
  lease_id?: Prisma.StringWithAggregatesFilter<"LeaseCurrentStatus"> | string
  lease_status_history_id?: Prisma.StringWithAggregatesFilter<"LeaseCurrentStatus"> | string
  lease_status_id?: Prisma.StringWithAggregatesFilter<"LeaseCurrentStatus"> | string
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"LeaseCurrentStatus"> | Date | string | null
}

export type LeaseCurrentStatusCreateInput = {
  lease_id: string
  deleted_at?: Date | string | null
  history: Prisma.LeaseStatusHistoryCreateNestedOneWithoutCurrentInput
  status: Prisma.LeaseStatusCreateNestedOneWithoutCurrentInput
}

export type LeaseCurrentStatusUncheckedCreateInput = {
  lease_id: string
  lease_status_history_id: string
  lease_status_id: string
  deleted_at?: Date | string | null
}

export type LeaseCurrentStatusUpdateInput = {
  lease_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  history?: Prisma.LeaseStatusHistoryUpdateOneRequiredWithoutCurrentNestedInput
  status?: Prisma.LeaseStatusUpdateOneRequiredWithoutCurrentNestedInput
}

export type LeaseCurrentStatusUncheckedUpdateInput = {
  lease_id?: Prisma.StringFieldUpdateOperationsInput | string
  lease_status_history_id?: Prisma.StringFieldUpdateOperationsInput | string
  lease_status_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LeaseCurrentStatusCreateManyInput = {
  lease_id: string
  lease_status_history_id: string
  lease_status_id: string
  deleted_at?: Date | string | null
}

export type LeaseCurrentStatusUpdateManyMutationInput = {
  lease_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LeaseCurrentStatusUncheckedUpdateManyInput = {
  lease_id?: Prisma.StringFieldUpdateOperationsInput | string
  lease_status_history_id?: Prisma.StringFieldUpdateOperationsInput | string
  lease_status_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LeaseCurrentStatusListRelationFilter = {
  every?: Prisma.LeaseCurrentStatusWhereInput
  some?: Prisma.LeaseCurrentStatusWhereInput
  none?: Prisma.LeaseCurrentStatusWhereInput
}

export type LeaseCurrentStatusOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LeaseCurrentStatusNullableScalarRelationFilter = {
  is?: Prisma.LeaseCurrentStatusWhereInput | null
  isNot?: Prisma.LeaseCurrentStatusWhereInput | null
}

export type LeaseCurrentStatusCountOrderByAggregateInput = {
  lease_id?: Prisma.SortOrder
  lease_status_history_id?: Prisma.SortOrder
  lease_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type LeaseCurrentStatusMaxOrderByAggregateInput = {
  lease_id?: Prisma.SortOrder
  lease_status_history_id?: Prisma.SortOrder
  lease_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type LeaseCurrentStatusMinOrderByAggregateInput = {
  lease_id?: Prisma.SortOrder
  lease_status_history_id?: Prisma.SortOrder
  lease_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type LeaseCurrentStatusCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutStatusInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput> | Prisma.LeaseCurrentStatusCreateWithoutStatusInput[] | Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.LeaseCurrentStatusCreateOrConnectWithoutStatusInput | Prisma.LeaseCurrentStatusCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.LeaseCurrentStatusCreateManyStatusInputEnvelope
  connect?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
}

export type LeaseCurrentStatusUncheckedCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutStatusInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput> | Prisma.LeaseCurrentStatusCreateWithoutStatusInput[] | Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.LeaseCurrentStatusCreateOrConnectWithoutStatusInput | Prisma.LeaseCurrentStatusCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.LeaseCurrentStatusCreateManyStatusInputEnvelope
  connect?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
}

export type LeaseCurrentStatusUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutStatusInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput> | Prisma.LeaseCurrentStatusCreateWithoutStatusInput[] | Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.LeaseCurrentStatusCreateOrConnectWithoutStatusInput | Prisma.LeaseCurrentStatusCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.LeaseCurrentStatusUpsertWithWhereUniqueWithoutStatusInput | Prisma.LeaseCurrentStatusUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.LeaseCurrentStatusCreateManyStatusInputEnvelope
  set?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
  disconnect?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
  delete?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
  connect?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
  update?: Prisma.LeaseCurrentStatusUpdateWithWhereUniqueWithoutStatusInput | Prisma.LeaseCurrentStatusUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.LeaseCurrentStatusUpdateManyWithWhereWithoutStatusInput | Prisma.LeaseCurrentStatusUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.LeaseCurrentStatusScalarWhereInput | Prisma.LeaseCurrentStatusScalarWhereInput[]
}

export type LeaseCurrentStatusUncheckedUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutStatusInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput> | Prisma.LeaseCurrentStatusCreateWithoutStatusInput[] | Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.LeaseCurrentStatusCreateOrConnectWithoutStatusInput | Prisma.LeaseCurrentStatusCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.LeaseCurrentStatusUpsertWithWhereUniqueWithoutStatusInput | Prisma.LeaseCurrentStatusUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.LeaseCurrentStatusCreateManyStatusInputEnvelope
  set?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
  disconnect?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
  delete?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
  connect?: Prisma.LeaseCurrentStatusWhereUniqueInput | Prisma.LeaseCurrentStatusWhereUniqueInput[]
  update?: Prisma.LeaseCurrentStatusUpdateWithWhereUniqueWithoutStatusInput | Prisma.LeaseCurrentStatusUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.LeaseCurrentStatusUpdateManyWithWhereWithoutStatusInput | Prisma.LeaseCurrentStatusUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.LeaseCurrentStatusScalarWhereInput | Prisma.LeaseCurrentStatusScalarWhereInput[]
}

export type LeaseCurrentStatusCreateNestedOneWithoutHistoryInput = {
  create?: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutHistoryInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.LeaseCurrentStatusCreateOrConnectWithoutHistoryInput
  connect?: Prisma.LeaseCurrentStatusWhereUniqueInput
}

export type LeaseCurrentStatusUncheckedCreateNestedOneWithoutHistoryInput = {
  create?: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutHistoryInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.LeaseCurrentStatusCreateOrConnectWithoutHistoryInput
  connect?: Prisma.LeaseCurrentStatusWhereUniqueInput
}

export type LeaseCurrentStatusUpdateOneWithoutHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutHistoryInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.LeaseCurrentStatusCreateOrConnectWithoutHistoryInput
  upsert?: Prisma.LeaseCurrentStatusUpsertWithoutHistoryInput
  disconnect?: Prisma.LeaseCurrentStatusWhereInput | boolean
  delete?: Prisma.LeaseCurrentStatusWhereInput | boolean
  connect?: Prisma.LeaseCurrentStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeaseCurrentStatusUpdateToOneWithWhereWithoutHistoryInput, Prisma.LeaseCurrentStatusUpdateWithoutHistoryInput>, Prisma.LeaseCurrentStatusUncheckedUpdateWithoutHistoryInput>
}

export type LeaseCurrentStatusUncheckedUpdateOneWithoutHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutHistoryInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.LeaseCurrentStatusCreateOrConnectWithoutHistoryInput
  upsert?: Prisma.LeaseCurrentStatusUpsertWithoutHistoryInput
  disconnect?: Prisma.LeaseCurrentStatusWhereInput | boolean
  delete?: Prisma.LeaseCurrentStatusWhereInput | boolean
  connect?: Prisma.LeaseCurrentStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeaseCurrentStatusUpdateToOneWithWhereWithoutHistoryInput, Prisma.LeaseCurrentStatusUpdateWithoutHistoryInput>, Prisma.LeaseCurrentStatusUncheckedUpdateWithoutHistoryInput>
}

export type LeaseCurrentStatusCreateWithoutStatusInput = {
  lease_id: string
  deleted_at?: Date | string | null
  history: Prisma.LeaseStatusHistoryCreateNestedOneWithoutCurrentInput
}

export type LeaseCurrentStatusUncheckedCreateWithoutStatusInput = {
  lease_id: string
  lease_status_history_id: string
  deleted_at?: Date | string | null
}

export type LeaseCurrentStatusCreateOrConnectWithoutStatusInput = {
  where: Prisma.LeaseCurrentStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutStatusInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput>
}

export type LeaseCurrentStatusCreateManyStatusInputEnvelope = {
  data: Prisma.LeaseCurrentStatusCreateManyStatusInput | Prisma.LeaseCurrentStatusCreateManyStatusInput[]
  skipDuplicates?: boolean
}

export type LeaseCurrentStatusUpsertWithWhereUniqueWithoutStatusInput = {
  where: Prisma.LeaseCurrentStatusWhereUniqueInput
  update: Prisma.XOR<Prisma.LeaseCurrentStatusUpdateWithoutStatusInput, Prisma.LeaseCurrentStatusUncheckedUpdateWithoutStatusInput>
  create: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutStatusInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutStatusInput>
}

export type LeaseCurrentStatusUpdateWithWhereUniqueWithoutStatusInput = {
  where: Prisma.LeaseCurrentStatusWhereUniqueInput
  data: Prisma.XOR<Prisma.LeaseCurrentStatusUpdateWithoutStatusInput, Prisma.LeaseCurrentStatusUncheckedUpdateWithoutStatusInput>
}

export type LeaseCurrentStatusUpdateManyWithWhereWithoutStatusInput = {
  where: Prisma.LeaseCurrentStatusScalarWhereInput
  data: Prisma.XOR<Prisma.LeaseCurrentStatusUpdateManyMutationInput, Prisma.LeaseCurrentStatusUncheckedUpdateManyWithoutStatusInput>
}

export type LeaseCurrentStatusScalarWhereInput = {
  AND?: Prisma.LeaseCurrentStatusScalarWhereInput | Prisma.LeaseCurrentStatusScalarWhereInput[]
  OR?: Prisma.LeaseCurrentStatusScalarWhereInput[]
  NOT?: Prisma.LeaseCurrentStatusScalarWhereInput | Prisma.LeaseCurrentStatusScalarWhereInput[]
  lease_id?: Prisma.StringFilter<"LeaseCurrentStatus"> | string
  lease_status_history_id?: Prisma.StringFilter<"LeaseCurrentStatus"> | string
  lease_status_id?: Prisma.StringFilter<"LeaseCurrentStatus"> | string
  deleted_at?: Prisma.DateTimeNullableFilter<"LeaseCurrentStatus"> | Date | string | null
}

export type LeaseCurrentStatusCreateWithoutHistoryInput = {
  lease_id: string
  deleted_at?: Date | string | null
  status: Prisma.LeaseStatusCreateNestedOneWithoutCurrentInput
}

export type LeaseCurrentStatusUncheckedCreateWithoutHistoryInput = {
  lease_id: string
  lease_status_id: string
  deleted_at?: Date | string | null
}

export type LeaseCurrentStatusCreateOrConnectWithoutHistoryInput = {
  where: Prisma.LeaseCurrentStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutHistoryInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutHistoryInput>
}

export type LeaseCurrentStatusUpsertWithoutHistoryInput = {
  update: Prisma.XOR<Prisma.LeaseCurrentStatusUpdateWithoutHistoryInput, Prisma.LeaseCurrentStatusUncheckedUpdateWithoutHistoryInput>
  create: Prisma.XOR<Prisma.LeaseCurrentStatusCreateWithoutHistoryInput, Prisma.LeaseCurrentStatusUncheckedCreateWithoutHistoryInput>
  where?: Prisma.LeaseCurrentStatusWhereInput
}

export type LeaseCurrentStatusUpdateToOneWithWhereWithoutHistoryInput = {
  where?: Prisma.LeaseCurrentStatusWhereInput
  data: Prisma.XOR<Prisma.LeaseCurrentStatusUpdateWithoutHistoryInput, Prisma.LeaseCurrentStatusUncheckedUpdateWithoutHistoryInput>
}

export type LeaseCurrentStatusUpdateWithoutHistoryInput = {
  lease_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.LeaseStatusUpdateOneRequiredWithoutCurrentNestedInput
}

export type LeaseCurrentStatusUncheckedUpdateWithoutHistoryInput = {
  lease_id?: Prisma.StringFieldUpdateOperationsInput | string
  lease_status_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LeaseCurrentStatusCreateManyStatusInput = {
  lease_id: string
  lease_status_history_id: string
  deleted_at?: Date | string | null
}

export type LeaseCurrentStatusUpdateWithoutStatusInput = {
  lease_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  history?: Prisma.LeaseStatusHistoryUpdateOneRequiredWithoutCurrentNestedInput
}

export type LeaseCurrentStatusUncheckedUpdateWithoutStatusInput = {
  lease_id?: Prisma.StringFieldUpdateOperationsInput | string
  lease_status_history_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LeaseCurrentStatusUncheckedUpdateManyWithoutStatusInput = {
  lease_id?: Prisma.StringFieldUpdateOperationsInput | string
  lease_status_history_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type LeaseCurrentStatusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  lease_id?: boolean
  lease_status_history_id?: boolean
  lease_status_id?: boolean
  deleted_at?: boolean
  history?: boolean | Prisma.LeaseStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.LeaseStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["leaseCurrentStatus"]>

export type LeaseCurrentStatusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  lease_id?: boolean
  lease_status_history_id?: boolean
  lease_status_id?: boolean
  deleted_at?: boolean
  history?: boolean | Prisma.LeaseStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.LeaseStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["leaseCurrentStatus"]>

export type LeaseCurrentStatusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  lease_id?: boolean
  lease_status_history_id?: boolean
  lease_status_id?: boolean
  deleted_at?: boolean
  history?: boolean | Prisma.LeaseStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.LeaseStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["leaseCurrentStatus"]>

export type LeaseCurrentStatusSelectScalar = {
  lease_id?: boolean
  lease_status_history_id?: boolean
  lease_status_id?: boolean
  deleted_at?: boolean
}

export type LeaseCurrentStatusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"lease_id" | "lease_status_history_id" | "lease_status_id" | "deleted_at", ExtArgs["result"]["leaseCurrentStatus"]>
export type LeaseCurrentStatusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  history?: boolean | Prisma.LeaseStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.LeaseStatusDefaultArgs<ExtArgs>
}
export type LeaseCurrentStatusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  history?: boolean | Prisma.LeaseStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.LeaseStatusDefaultArgs<ExtArgs>
}
export type LeaseCurrentStatusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  history?: boolean | Prisma.LeaseStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.LeaseStatusDefaultArgs<ExtArgs>
}

export type $LeaseCurrentStatusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LeaseCurrentStatus"
  objects: {
    history: Prisma.$LeaseStatusHistoryPayload<ExtArgs>
    status: Prisma.$LeaseStatusPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    lease_id: string
    lease_status_history_id: string
    lease_status_id: string
    deleted_at: Date | null
  }, ExtArgs["result"]["leaseCurrentStatus"]>
  composites: {}
}

export type LeaseCurrentStatusGetPayload<S extends boolean | null | undefined | LeaseCurrentStatusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload, S>

export type LeaseCurrentStatusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LeaseCurrentStatusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LeaseCurrentStatusCountAggregateInputType | true
  }

export interface LeaseCurrentStatusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LeaseCurrentStatus'], meta: { name: 'LeaseCurrentStatus' } }
  /**
   * Find zero or one LeaseCurrentStatus that matches the filter.
   * @param {LeaseCurrentStatusFindUniqueArgs} args - Arguments to find a LeaseCurrentStatus
   * @example
   * // Get one LeaseCurrentStatus
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LeaseCurrentStatusFindUniqueArgs>(args: Prisma.SelectSubset<T, LeaseCurrentStatusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LeaseCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LeaseCurrentStatus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LeaseCurrentStatusFindUniqueOrThrowArgs} args - Arguments to find a LeaseCurrentStatus
   * @example
   * // Get one LeaseCurrentStatus
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LeaseCurrentStatusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LeaseCurrentStatusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeaseCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LeaseCurrentStatus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseCurrentStatusFindFirstArgs} args - Arguments to find a LeaseCurrentStatus
   * @example
   * // Get one LeaseCurrentStatus
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LeaseCurrentStatusFindFirstArgs>(args?: Prisma.SelectSubset<T, LeaseCurrentStatusFindFirstArgs<ExtArgs>>): Prisma.Prisma__LeaseCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LeaseCurrentStatus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseCurrentStatusFindFirstOrThrowArgs} args - Arguments to find a LeaseCurrentStatus
   * @example
   * // Get one LeaseCurrentStatus
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LeaseCurrentStatusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LeaseCurrentStatusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeaseCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LeaseCurrentStatuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseCurrentStatusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LeaseCurrentStatuses
   * const leaseCurrentStatuses = await prisma.leaseCurrentStatus.findMany()
   * 
   * // Get first 10 LeaseCurrentStatuses
   * const leaseCurrentStatuses = await prisma.leaseCurrentStatus.findMany({ take: 10 })
   * 
   * // Only select the `lease_id`
   * const leaseCurrentStatusWithLease_idOnly = await prisma.leaseCurrentStatus.findMany({ select: { lease_id: true } })
   * 
   */
  findMany<T extends LeaseCurrentStatusFindManyArgs>(args?: Prisma.SelectSubset<T, LeaseCurrentStatusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LeaseCurrentStatus.
   * @param {LeaseCurrentStatusCreateArgs} args - Arguments to create a LeaseCurrentStatus.
   * @example
   * // Create one LeaseCurrentStatus
   * const LeaseCurrentStatus = await prisma.leaseCurrentStatus.create({
   *   data: {
   *     // ... data to create a LeaseCurrentStatus
   *   }
   * })
   * 
   */
  create<T extends LeaseCurrentStatusCreateArgs>(args: Prisma.SelectSubset<T, LeaseCurrentStatusCreateArgs<ExtArgs>>): Prisma.Prisma__LeaseCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LeaseCurrentStatuses.
   * @param {LeaseCurrentStatusCreateManyArgs} args - Arguments to create many LeaseCurrentStatuses.
   * @example
   * // Create many LeaseCurrentStatuses
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LeaseCurrentStatusCreateManyArgs>(args?: Prisma.SelectSubset<T, LeaseCurrentStatusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LeaseCurrentStatuses and returns the data saved in the database.
   * @param {LeaseCurrentStatusCreateManyAndReturnArgs} args - Arguments to create many LeaseCurrentStatuses.
   * @example
   * // Create many LeaseCurrentStatuses
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LeaseCurrentStatuses and only return the `lease_id`
   * const leaseCurrentStatusWithLease_idOnly = await prisma.leaseCurrentStatus.createManyAndReturn({
   *   select: { lease_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LeaseCurrentStatusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LeaseCurrentStatusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LeaseCurrentStatus.
   * @param {LeaseCurrentStatusDeleteArgs} args - Arguments to delete one LeaseCurrentStatus.
   * @example
   * // Delete one LeaseCurrentStatus
   * const LeaseCurrentStatus = await prisma.leaseCurrentStatus.delete({
   *   where: {
   *     // ... filter to delete one LeaseCurrentStatus
   *   }
   * })
   * 
   */
  delete<T extends LeaseCurrentStatusDeleteArgs>(args: Prisma.SelectSubset<T, LeaseCurrentStatusDeleteArgs<ExtArgs>>): Prisma.Prisma__LeaseCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LeaseCurrentStatus.
   * @param {LeaseCurrentStatusUpdateArgs} args - Arguments to update one LeaseCurrentStatus.
   * @example
   * // Update one LeaseCurrentStatus
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LeaseCurrentStatusUpdateArgs>(args: Prisma.SelectSubset<T, LeaseCurrentStatusUpdateArgs<ExtArgs>>): Prisma.Prisma__LeaseCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LeaseCurrentStatuses.
   * @param {LeaseCurrentStatusDeleteManyArgs} args - Arguments to filter LeaseCurrentStatuses to delete.
   * @example
   * // Delete a few LeaseCurrentStatuses
   * const { count } = await prisma.leaseCurrentStatus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LeaseCurrentStatusDeleteManyArgs>(args?: Prisma.SelectSubset<T, LeaseCurrentStatusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LeaseCurrentStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseCurrentStatusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LeaseCurrentStatuses
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LeaseCurrentStatusUpdateManyArgs>(args: Prisma.SelectSubset<T, LeaseCurrentStatusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LeaseCurrentStatuses and returns the data updated in the database.
   * @param {LeaseCurrentStatusUpdateManyAndReturnArgs} args - Arguments to update many LeaseCurrentStatuses.
   * @example
   * // Update many LeaseCurrentStatuses
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LeaseCurrentStatuses and only return the `lease_id`
   * const leaseCurrentStatusWithLease_idOnly = await prisma.leaseCurrentStatus.updateManyAndReturn({
   *   select: { lease_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LeaseCurrentStatusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LeaseCurrentStatusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LeaseCurrentStatus.
   * @param {LeaseCurrentStatusUpsertArgs} args - Arguments to update or create a LeaseCurrentStatus.
   * @example
   * // Update or create a LeaseCurrentStatus
   * const leaseCurrentStatus = await prisma.leaseCurrentStatus.upsert({
   *   create: {
   *     // ... data to create a LeaseCurrentStatus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LeaseCurrentStatus we want to update
   *   }
   * })
   */
  upsert<T extends LeaseCurrentStatusUpsertArgs>(args: Prisma.SelectSubset<T, LeaseCurrentStatusUpsertArgs<ExtArgs>>): Prisma.Prisma__LeaseCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$LeaseCurrentStatusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LeaseCurrentStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseCurrentStatusCountArgs} args - Arguments to filter LeaseCurrentStatuses to count.
   * @example
   * // Count the number of LeaseCurrentStatuses
   * const count = await prisma.leaseCurrentStatus.count({
   *   where: {
   *     // ... the filter for the LeaseCurrentStatuses we want to count
   *   }
   * })
  **/
  count<T extends LeaseCurrentStatusCountArgs>(
    args?: Prisma.Subset<T, LeaseCurrentStatusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LeaseCurrentStatusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LeaseCurrentStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseCurrentStatusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LeaseCurrentStatusAggregateArgs>(args: Prisma.Subset<T, LeaseCurrentStatusAggregateArgs>): Prisma.PrismaPromise<GetLeaseCurrentStatusAggregateType<T>>

  /**
   * Group by LeaseCurrentStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseCurrentStatusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LeaseCurrentStatusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LeaseCurrentStatusGroupByArgs['orderBy'] }
      : { orderBy?: LeaseCurrentStatusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LeaseCurrentStatusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLeaseCurrentStatusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LeaseCurrentStatus model
 */
readonly fields: LeaseCurrentStatusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LeaseCurrentStatus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LeaseCurrentStatusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  history<T extends Prisma.LeaseStatusHistoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LeaseStatusHistoryDefaultArgs<ExtArgs>>): Prisma.Prisma__LeaseStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$LeaseStatusHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  status<T extends Prisma.LeaseStatusDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LeaseStatusDefaultArgs<ExtArgs>>): Prisma.Prisma__LeaseStatusClient<runtime.Types.Result.GetResult<Prisma.$LeaseStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LeaseCurrentStatus model
 */
export interface LeaseCurrentStatusFieldRefs {
  readonly lease_id: Prisma.FieldRef<"LeaseCurrentStatus", 'String'>
  readonly lease_status_history_id: Prisma.FieldRef<"LeaseCurrentStatus", 'String'>
  readonly lease_status_id: Prisma.FieldRef<"LeaseCurrentStatus", 'String'>
  readonly deleted_at: Prisma.FieldRef<"LeaseCurrentStatus", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LeaseCurrentStatus findUnique
 */
export type LeaseCurrentStatusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which LeaseCurrentStatus to fetch.
   */
  where: Prisma.LeaseCurrentStatusWhereUniqueInput
}

/**
 * LeaseCurrentStatus findUniqueOrThrow
 */
export type LeaseCurrentStatusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which LeaseCurrentStatus to fetch.
   */
  where: Prisma.LeaseCurrentStatusWhereUniqueInput
}

/**
 * LeaseCurrentStatus findFirst
 */
export type LeaseCurrentStatusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which LeaseCurrentStatus to fetch.
   */
  where?: Prisma.LeaseCurrentStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LeaseCurrentStatuses to fetch.
   */
  orderBy?: Prisma.LeaseCurrentStatusOrderByWithRelationInput | Prisma.LeaseCurrentStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LeaseCurrentStatuses.
   */
  cursor?: Prisma.LeaseCurrentStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LeaseCurrentStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LeaseCurrentStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LeaseCurrentStatuses.
   */
  distinct?: Prisma.LeaseCurrentStatusScalarFieldEnum | Prisma.LeaseCurrentStatusScalarFieldEnum[]
}

/**
 * LeaseCurrentStatus findFirstOrThrow
 */
export type LeaseCurrentStatusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which LeaseCurrentStatus to fetch.
   */
  where?: Prisma.LeaseCurrentStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LeaseCurrentStatuses to fetch.
   */
  orderBy?: Prisma.LeaseCurrentStatusOrderByWithRelationInput | Prisma.LeaseCurrentStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LeaseCurrentStatuses.
   */
  cursor?: Prisma.LeaseCurrentStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LeaseCurrentStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LeaseCurrentStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LeaseCurrentStatuses.
   */
  distinct?: Prisma.LeaseCurrentStatusScalarFieldEnum | Prisma.LeaseCurrentStatusScalarFieldEnum[]
}

/**
 * LeaseCurrentStatus findMany
 */
export type LeaseCurrentStatusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which LeaseCurrentStatuses to fetch.
   */
  where?: Prisma.LeaseCurrentStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LeaseCurrentStatuses to fetch.
   */
  orderBy?: Prisma.LeaseCurrentStatusOrderByWithRelationInput | Prisma.LeaseCurrentStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LeaseCurrentStatuses.
   */
  cursor?: Prisma.LeaseCurrentStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LeaseCurrentStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LeaseCurrentStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LeaseCurrentStatuses.
   */
  distinct?: Prisma.LeaseCurrentStatusScalarFieldEnum | Prisma.LeaseCurrentStatusScalarFieldEnum[]
}

/**
 * LeaseCurrentStatus create
 */
export type LeaseCurrentStatusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
  /**
   * The data needed to create a LeaseCurrentStatus.
   */
  data: Prisma.XOR<Prisma.LeaseCurrentStatusCreateInput, Prisma.LeaseCurrentStatusUncheckedCreateInput>
}

/**
 * LeaseCurrentStatus createMany
 */
export type LeaseCurrentStatusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LeaseCurrentStatuses.
   */
  data: Prisma.LeaseCurrentStatusCreateManyInput | Prisma.LeaseCurrentStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LeaseCurrentStatus createManyAndReturn
 */
export type LeaseCurrentStatusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * The data used to create many LeaseCurrentStatuses.
   */
  data: Prisma.LeaseCurrentStatusCreateManyInput | Prisma.LeaseCurrentStatusCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LeaseCurrentStatus update
 */
export type LeaseCurrentStatusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
  /**
   * The data needed to update a LeaseCurrentStatus.
   */
  data: Prisma.XOR<Prisma.LeaseCurrentStatusUpdateInput, Prisma.LeaseCurrentStatusUncheckedUpdateInput>
  /**
   * Choose, which LeaseCurrentStatus to update.
   */
  where: Prisma.LeaseCurrentStatusWhereUniqueInput
}

/**
 * LeaseCurrentStatus updateMany
 */
export type LeaseCurrentStatusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LeaseCurrentStatuses.
   */
  data: Prisma.XOR<Prisma.LeaseCurrentStatusUpdateManyMutationInput, Prisma.LeaseCurrentStatusUncheckedUpdateManyInput>
  /**
   * Filter which LeaseCurrentStatuses to update
   */
  where?: Prisma.LeaseCurrentStatusWhereInput
  /**
   * Limit how many LeaseCurrentStatuses to update.
   */
  limit?: number
}

/**
 * LeaseCurrentStatus updateManyAndReturn
 */
export type LeaseCurrentStatusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * The data used to update LeaseCurrentStatuses.
   */
  data: Prisma.XOR<Prisma.LeaseCurrentStatusUpdateManyMutationInput, Prisma.LeaseCurrentStatusUncheckedUpdateManyInput>
  /**
   * Filter which LeaseCurrentStatuses to update
   */
  where?: Prisma.LeaseCurrentStatusWhereInput
  /**
   * Limit how many LeaseCurrentStatuses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LeaseCurrentStatus upsert
 */
export type LeaseCurrentStatusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
  /**
   * The filter to search for the LeaseCurrentStatus to update in case it exists.
   */
  where: Prisma.LeaseCurrentStatusWhereUniqueInput
  /**
   * In case the LeaseCurrentStatus found by the `where` argument doesn't exist, create a new LeaseCurrentStatus with this data.
   */
  create: Prisma.XOR<Prisma.LeaseCurrentStatusCreateInput, Prisma.LeaseCurrentStatusUncheckedCreateInput>
  /**
   * In case the LeaseCurrentStatus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LeaseCurrentStatusUpdateInput, Prisma.LeaseCurrentStatusUncheckedUpdateInput>
}

/**
 * LeaseCurrentStatus delete
 */
export type LeaseCurrentStatusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter which LeaseCurrentStatus to delete.
   */
  where: Prisma.LeaseCurrentStatusWhereUniqueInput
}

/**
 * LeaseCurrentStatus deleteMany
 */
export type LeaseCurrentStatusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LeaseCurrentStatuses to delete
   */
  where?: Prisma.LeaseCurrentStatusWhereInput
  /**
   * Limit how many LeaseCurrentStatuses to delete.
   */
  limit?: number
}

/**
 * LeaseCurrentStatus without action
 */
export type LeaseCurrentStatusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCurrentStatus
   */
  select?: Prisma.LeaseCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaseCurrentStatus
   */
  omit?: Prisma.LeaseCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseCurrentStatusInclude<ExtArgs> | null
}
