
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ListingCurrentStatus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ListingCurrentStatus
 * 
 */
export type ListingCurrentStatusModel = runtime.Types.Result.DefaultSelection<Prisma.$ListingCurrentStatusPayload>

export type AggregateListingCurrentStatus = {
  _count: ListingCurrentStatusCountAggregateOutputType | null
  _min: ListingCurrentStatusMinAggregateOutputType | null
  _max: ListingCurrentStatusMaxAggregateOutputType | null
}

export type ListingCurrentStatusMinAggregateOutputType = {
  listing_id: string | null
  listing_status_history_id: string | null
  listing_status_id: string | null
  deleted_at: Date | null
}

export type ListingCurrentStatusMaxAggregateOutputType = {
  listing_id: string | null
  listing_status_history_id: string | null
  listing_status_id: string | null
  deleted_at: Date | null
}

export type ListingCurrentStatusCountAggregateOutputType = {
  listing_id: number
  listing_status_history_id: number
  listing_status_id: number
  deleted_at: number
  _all: number
}


export type ListingCurrentStatusMinAggregateInputType = {
  listing_id?: true
  listing_status_history_id?: true
  listing_status_id?: true
  deleted_at?: true
}

export type ListingCurrentStatusMaxAggregateInputType = {
  listing_id?: true
  listing_status_history_id?: true
  listing_status_id?: true
  deleted_at?: true
}

export type ListingCurrentStatusCountAggregateInputType = {
  listing_id?: true
  listing_status_history_id?: true
  listing_status_id?: true
  deleted_at?: true
  _all?: true
}

export type ListingCurrentStatusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingCurrentStatus to aggregate.
   */
  where?: Prisma.ListingCurrentStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingCurrentStatuses to fetch.
   */
  orderBy?: Prisma.ListingCurrentStatusOrderByWithRelationInput | Prisma.ListingCurrentStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ListingCurrentStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingCurrentStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingCurrentStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ListingCurrentStatuses
  **/
  _count?: true | ListingCurrentStatusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ListingCurrentStatusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ListingCurrentStatusMaxAggregateInputType
}

export type GetListingCurrentStatusAggregateType<T extends ListingCurrentStatusAggregateArgs> = {
      [P in keyof T & keyof AggregateListingCurrentStatus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateListingCurrentStatus[P]>
    : Prisma.GetScalarType<T[P], AggregateListingCurrentStatus[P]>
}




export type ListingCurrentStatusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingCurrentStatusWhereInput
  orderBy?: Prisma.ListingCurrentStatusOrderByWithAggregationInput | Prisma.ListingCurrentStatusOrderByWithAggregationInput[]
  by: Prisma.ListingCurrentStatusScalarFieldEnum[] | Prisma.ListingCurrentStatusScalarFieldEnum
  having?: Prisma.ListingCurrentStatusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ListingCurrentStatusCountAggregateInputType | true
  _min?: ListingCurrentStatusMinAggregateInputType
  _max?: ListingCurrentStatusMaxAggregateInputType
}

export type ListingCurrentStatusGroupByOutputType = {
  listing_id: string
  listing_status_history_id: string
  listing_status_id: string
  deleted_at: Date | null
  _count: ListingCurrentStatusCountAggregateOutputType | null
  _min: ListingCurrentStatusMinAggregateOutputType | null
  _max: ListingCurrentStatusMaxAggregateOutputType | null
}

export type GetListingCurrentStatusGroupByPayload<T extends ListingCurrentStatusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ListingCurrentStatusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ListingCurrentStatusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ListingCurrentStatusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ListingCurrentStatusGroupByOutputType[P]>
      }
    >
  >



export type ListingCurrentStatusWhereInput = {
  AND?: Prisma.ListingCurrentStatusWhereInput | Prisma.ListingCurrentStatusWhereInput[]
  OR?: Prisma.ListingCurrentStatusWhereInput[]
  NOT?: Prisma.ListingCurrentStatusWhereInput | Prisma.ListingCurrentStatusWhereInput[]
  listing_id?: Prisma.StringFilter<"ListingCurrentStatus"> | string
  listing_status_history_id?: Prisma.StringFilter<"ListingCurrentStatus"> | string
  listing_status_id?: Prisma.StringFilter<"ListingCurrentStatus"> | string
  deleted_at?: Prisma.DateTimeNullableFilter<"ListingCurrentStatus"> | Date | string | null
  history?: Prisma.XOR<Prisma.ListingStatusHistoryScalarRelationFilter, Prisma.ListingStatusHistoryWhereInput>
  status?: Prisma.XOR<Prisma.ListingStatusScalarRelationFilter, Prisma.ListingStatusWhereInput>
}

export type ListingCurrentStatusOrderByWithRelationInput = {
  listing_id?: Prisma.SortOrder
  listing_status_history_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  history?: Prisma.ListingStatusHistoryOrderByWithRelationInput
  status?: Prisma.ListingStatusOrderByWithRelationInput
}

export type ListingCurrentStatusWhereUniqueInput = Prisma.AtLeast<{
  listing_id?: string
  listing_status_history_id?: string
  AND?: Prisma.ListingCurrentStatusWhereInput | Prisma.ListingCurrentStatusWhereInput[]
  OR?: Prisma.ListingCurrentStatusWhereInput[]
  NOT?: Prisma.ListingCurrentStatusWhereInput | Prisma.ListingCurrentStatusWhereInput[]
  listing_status_id?: Prisma.StringFilter<"ListingCurrentStatus"> | string
  deleted_at?: Prisma.DateTimeNullableFilter<"ListingCurrentStatus"> | Date | string | null
  history?: Prisma.XOR<Prisma.ListingStatusHistoryScalarRelationFilter, Prisma.ListingStatusHistoryWhereInput>
  status?: Prisma.XOR<Prisma.ListingStatusScalarRelationFilter, Prisma.ListingStatusWhereInput>
}, "listing_id" | "listing_status_history_id">

export type ListingCurrentStatusOrderByWithAggregationInput = {
  listing_id?: Prisma.SortOrder
  listing_status_history_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ListingCurrentStatusCountOrderByAggregateInput
  _max?: Prisma.ListingCurrentStatusMaxOrderByAggregateInput
  _min?: Prisma.ListingCurrentStatusMinOrderByAggregateInput
}

export type ListingCurrentStatusScalarWhereWithAggregatesInput = {
  AND?: Prisma.ListingCurrentStatusScalarWhereWithAggregatesInput | Prisma.ListingCurrentStatusScalarWhereWithAggregatesInput[]
  OR?: Prisma.ListingCurrentStatusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ListingCurrentStatusScalarWhereWithAggregatesInput | Prisma.ListingCurrentStatusScalarWhereWithAggregatesInput[]
  listing_id?: Prisma.StringWithAggregatesFilter<"ListingCurrentStatus"> | string
  listing_status_history_id?: Prisma.StringWithAggregatesFilter<"ListingCurrentStatus"> | string
  listing_status_id?: Prisma.StringWithAggregatesFilter<"ListingCurrentStatus"> | string
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"ListingCurrentStatus"> | Date | string | null
}

export type ListingCurrentStatusCreateInput = {
  listing_id: string
  deleted_at?: Date | string | null
  history: Prisma.ListingStatusHistoryCreateNestedOneWithoutCurrentInput
  status: Prisma.ListingStatusCreateNestedOneWithoutCurrentInput
}

export type ListingCurrentStatusUncheckedCreateInput = {
  listing_id: string
  listing_status_history_id: string
  listing_status_id: string
  deleted_at?: Date | string | null
}

export type ListingCurrentStatusUpdateInput = {
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  history?: Prisma.ListingStatusHistoryUpdateOneRequiredWithoutCurrentNestedInput
  status?: Prisma.ListingStatusUpdateOneRequiredWithoutCurrentNestedInput
}

export type ListingCurrentStatusUncheckedUpdateInput = {
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_history_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ListingCurrentStatusCreateManyInput = {
  listing_id: string
  listing_status_history_id: string
  listing_status_id: string
  deleted_at?: Date | string | null
}

export type ListingCurrentStatusUpdateManyMutationInput = {
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ListingCurrentStatusUncheckedUpdateManyInput = {
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_history_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ListingCurrentStatusListRelationFilter = {
  every?: Prisma.ListingCurrentStatusWhereInput
  some?: Prisma.ListingCurrentStatusWhereInput
  none?: Prisma.ListingCurrentStatusWhereInput
}

export type ListingCurrentStatusOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ListingCurrentStatusNullableScalarRelationFilter = {
  is?: Prisma.ListingCurrentStatusWhereInput | null
  isNot?: Prisma.ListingCurrentStatusWhereInput | null
}

export type ListingCurrentStatusCountOrderByAggregateInput = {
  listing_id?: Prisma.SortOrder
  listing_status_history_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type ListingCurrentStatusMaxOrderByAggregateInput = {
  listing_id?: Prisma.SortOrder
  listing_status_history_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type ListingCurrentStatusMinOrderByAggregateInput = {
  listing_id?: Prisma.SortOrder
  listing_status_history_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type ListingCurrentStatusCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutStatusInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput> | Prisma.ListingCurrentStatusCreateWithoutStatusInput[] | Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.ListingCurrentStatusCreateOrConnectWithoutStatusInput | Prisma.ListingCurrentStatusCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.ListingCurrentStatusCreateManyStatusInputEnvelope
  connect?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
}

export type ListingCurrentStatusUncheckedCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutStatusInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput> | Prisma.ListingCurrentStatusCreateWithoutStatusInput[] | Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.ListingCurrentStatusCreateOrConnectWithoutStatusInput | Prisma.ListingCurrentStatusCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.ListingCurrentStatusCreateManyStatusInputEnvelope
  connect?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
}

export type ListingCurrentStatusUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutStatusInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput> | Prisma.ListingCurrentStatusCreateWithoutStatusInput[] | Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.ListingCurrentStatusCreateOrConnectWithoutStatusInput | Prisma.ListingCurrentStatusCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.ListingCurrentStatusUpsertWithWhereUniqueWithoutStatusInput | Prisma.ListingCurrentStatusUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.ListingCurrentStatusCreateManyStatusInputEnvelope
  set?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
  disconnect?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
  delete?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
  connect?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
  update?: Prisma.ListingCurrentStatusUpdateWithWhereUniqueWithoutStatusInput | Prisma.ListingCurrentStatusUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.ListingCurrentStatusUpdateManyWithWhereWithoutStatusInput | Prisma.ListingCurrentStatusUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.ListingCurrentStatusScalarWhereInput | Prisma.ListingCurrentStatusScalarWhereInput[]
}

export type ListingCurrentStatusUncheckedUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutStatusInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput> | Prisma.ListingCurrentStatusCreateWithoutStatusInput[] | Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.ListingCurrentStatusCreateOrConnectWithoutStatusInput | Prisma.ListingCurrentStatusCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.ListingCurrentStatusUpsertWithWhereUniqueWithoutStatusInput | Prisma.ListingCurrentStatusUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.ListingCurrentStatusCreateManyStatusInputEnvelope
  set?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
  disconnect?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
  delete?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
  connect?: Prisma.ListingCurrentStatusWhereUniqueInput | Prisma.ListingCurrentStatusWhereUniqueInput[]
  update?: Prisma.ListingCurrentStatusUpdateWithWhereUniqueWithoutStatusInput | Prisma.ListingCurrentStatusUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.ListingCurrentStatusUpdateManyWithWhereWithoutStatusInput | Prisma.ListingCurrentStatusUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.ListingCurrentStatusScalarWhereInput | Prisma.ListingCurrentStatusScalarWhereInput[]
}

export type ListingCurrentStatusCreateNestedOneWithoutHistoryInput = {
  create?: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutHistoryInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.ListingCurrentStatusCreateOrConnectWithoutHistoryInput
  connect?: Prisma.ListingCurrentStatusWhereUniqueInput
}

export type ListingCurrentStatusUncheckedCreateNestedOneWithoutHistoryInput = {
  create?: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutHistoryInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.ListingCurrentStatusCreateOrConnectWithoutHistoryInput
  connect?: Prisma.ListingCurrentStatusWhereUniqueInput
}

export type ListingCurrentStatusUpdateOneWithoutHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutHistoryInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.ListingCurrentStatusCreateOrConnectWithoutHistoryInput
  upsert?: Prisma.ListingCurrentStatusUpsertWithoutHistoryInput
  disconnect?: Prisma.ListingCurrentStatusWhereInput | boolean
  delete?: Prisma.ListingCurrentStatusWhereInput | boolean
  connect?: Prisma.ListingCurrentStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListingCurrentStatusUpdateToOneWithWhereWithoutHistoryInput, Prisma.ListingCurrentStatusUpdateWithoutHistoryInput>, Prisma.ListingCurrentStatusUncheckedUpdateWithoutHistoryInput>
}

export type ListingCurrentStatusUncheckedUpdateOneWithoutHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutHistoryInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.ListingCurrentStatusCreateOrConnectWithoutHistoryInput
  upsert?: Prisma.ListingCurrentStatusUpsertWithoutHistoryInput
  disconnect?: Prisma.ListingCurrentStatusWhereInput | boolean
  delete?: Prisma.ListingCurrentStatusWhereInput | boolean
  connect?: Prisma.ListingCurrentStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListingCurrentStatusUpdateToOneWithWhereWithoutHistoryInput, Prisma.ListingCurrentStatusUpdateWithoutHistoryInput>, Prisma.ListingCurrentStatusUncheckedUpdateWithoutHistoryInput>
}

export type ListingCurrentStatusCreateWithoutStatusInput = {
  listing_id: string
  deleted_at?: Date | string | null
  history: Prisma.ListingStatusHistoryCreateNestedOneWithoutCurrentInput
}

export type ListingCurrentStatusUncheckedCreateWithoutStatusInput = {
  listing_id: string
  listing_status_history_id: string
  deleted_at?: Date | string | null
}

export type ListingCurrentStatusCreateOrConnectWithoutStatusInput = {
  where: Prisma.ListingCurrentStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutStatusInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput>
}

export type ListingCurrentStatusCreateManyStatusInputEnvelope = {
  data: Prisma.ListingCurrentStatusCreateManyStatusInput | Prisma.ListingCurrentStatusCreateManyStatusInput[]
  skipDuplicates?: boolean
}

export type ListingCurrentStatusUpsertWithWhereUniqueWithoutStatusInput = {
  where: Prisma.ListingCurrentStatusWhereUniqueInput
  update: Prisma.XOR<Prisma.ListingCurrentStatusUpdateWithoutStatusInput, Prisma.ListingCurrentStatusUncheckedUpdateWithoutStatusInput>
  create: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutStatusInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutStatusInput>
}

export type ListingCurrentStatusUpdateWithWhereUniqueWithoutStatusInput = {
  where: Prisma.ListingCurrentStatusWhereUniqueInput
  data: Prisma.XOR<Prisma.ListingCurrentStatusUpdateWithoutStatusInput, Prisma.ListingCurrentStatusUncheckedUpdateWithoutStatusInput>
}

export type ListingCurrentStatusUpdateManyWithWhereWithoutStatusInput = {
  where: Prisma.ListingCurrentStatusScalarWhereInput
  data: Prisma.XOR<Prisma.ListingCurrentStatusUpdateManyMutationInput, Prisma.ListingCurrentStatusUncheckedUpdateManyWithoutStatusInput>
}

export type ListingCurrentStatusScalarWhereInput = {
  AND?: Prisma.ListingCurrentStatusScalarWhereInput | Prisma.ListingCurrentStatusScalarWhereInput[]
  OR?: Prisma.ListingCurrentStatusScalarWhereInput[]
  NOT?: Prisma.ListingCurrentStatusScalarWhereInput | Prisma.ListingCurrentStatusScalarWhereInput[]
  listing_id?: Prisma.StringFilter<"ListingCurrentStatus"> | string
  listing_status_history_id?: Prisma.StringFilter<"ListingCurrentStatus"> | string
  listing_status_id?: Prisma.StringFilter<"ListingCurrentStatus"> | string
  deleted_at?: Prisma.DateTimeNullableFilter<"ListingCurrentStatus"> | Date | string | null
}

export type ListingCurrentStatusCreateWithoutHistoryInput = {
  listing_id: string
  deleted_at?: Date | string | null
  status: Prisma.ListingStatusCreateNestedOneWithoutCurrentInput
}

export type ListingCurrentStatusUncheckedCreateWithoutHistoryInput = {
  listing_id: string
  listing_status_id: string
  deleted_at?: Date | string | null
}

export type ListingCurrentStatusCreateOrConnectWithoutHistoryInput = {
  where: Prisma.ListingCurrentStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutHistoryInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutHistoryInput>
}

export type ListingCurrentStatusUpsertWithoutHistoryInput = {
  update: Prisma.XOR<Prisma.ListingCurrentStatusUpdateWithoutHistoryInput, Prisma.ListingCurrentStatusUncheckedUpdateWithoutHistoryInput>
  create: Prisma.XOR<Prisma.ListingCurrentStatusCreateWithoutHistoryInput, Prisma.ListingCurrentStatusUncheckedCreateWithoutHistoryInput>
  where?: Prisma.ListingCurrentStatusWhereInput
}

export type ListingCurrentStatusUpdateToOneWithWhereWithoutHistoryInput = {
  where?: Prisma.ListingCurrentStatusWhereInput
  data: Prisma.XOR<Prisma.ListingCurrentStatusUpdateWithoutHistoryInput, Prisma.ListingCurrentStatusUncheckedUpdateWithoutHistoryInput>
}

export type ListingCurrentStatusUpdateWithoutHistoryInput = {
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.ListingStatusUpdateOneRequiredWithoutCurrentNestedInput
}

export type ListingCurrentStatusUncheckedUpdateWithoutHistoryInput = {
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ListingCurrentStatusCreateManyStatusInput = {
  listing_id: string
  listing_status_history_id: string
  deleted_at?: Date | string | null
}

export type ListingCurrentStatusUpdateWithoutStatusInput = {
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  history?: Prisma.ListingStatusHistoryUpdateOneRequiredWithoutCurrentNestedInput
}

export type ListingCurrentStatusUncheckedUpdateWithoutStatusInput = {
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_history_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ListingCurrentStatusUncheckedUpdateManyWithoutStatusInput = {
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_history_id?: Prisma.StringFieldUpdateOperationsInput | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type ListingCurrentStatusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  listing_id?: boolean
  listing_status_history_id?: boolean
  listing_status_id?: boolean
  deleted_at?: boolean
  history?: boolean | Prisma.ListingStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingCurrentStatus"]>

export type ListingCurrentStatusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  listing_id?: boolean
  listing_status_history_id?: boolean
  listing_status_id?: boolean
  deleted_at?: boolean
  history?: boolean | Prisma.ListingStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingCurrentStatus"]>

export type ListingCurrentStatusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  listing_id?: boolean
  listing_status_history_id?: boolean
  listing_status_id?: boolean
  deleted_at?: boolean
  history?: boolean | Prisma.ListingStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingCurrentStatus"]>

export type ListingCurrentStatusSelectScalar = {
  listing_id?: boolean
  listing_status_history_id?: boolean
  listing_status_id?: boolean
  deleted_at?: boolean
}

export type ListingCurrentStatusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"listing_id" | "listing_status_history_id" | "listing_status_id" | "deleted_at", ExtArgs["result"]["listingCurrentStatus"]>
export type ListingCurrentStatusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  history?: boolean | Prisma.ListingStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}
export type ListingCurrentStatusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  history?: boolean | Prisma.ListingStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}
export type ListingCurrentStatusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  history?: boolean | Prisma.ListingStatusHistoryDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}

export type $ListingCurrentStatusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ListingCurrentStatus"
  objects: {
    history: Prisma.$ListingStatusHistoryPayload<ExtArgs>
    status: Prisma.$ListingStatusPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    listing_id: string
    listing_status_history_id: string
    listing_status_id: string
    deleted_at: Date | null
  }, ExtArgs["result"]["listingCurrentStatus"]>
  composites: {}
}

export type ListingCurrentStatusGetPayload<S extends boolean | null | undefined | ListingCurrentStatusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload, S>

export type ListingCurrentStatusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ListingCurrentStatusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ListingCurrentStatusCountAggregateInputType | true
  }

export interface ListingCurrentStatusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ListingCurrentStatus'], meta: { name: 'ListingCurrentStatus' } }
  /**
   * Find zero or one ListingCurrentStatus that matches the filter.
   * @param {ListingCurrentStatusFindUniqueArgs} args - Arguments to find a ListingCurrentStatus
   * @example
   * // Get one ListingCurrentStatus
   * const listingCurrentStatus = await prisma.listingCurrentStatus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ListingCurrentStatusFindUniqueArgs>(args: Prisma.SelectSubset<T, ListingCurrentStatusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ListingCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ListingCurrentStatus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ListingCurrentStatusFindUniqueOrThrowArgs} args - Arguments to find a ListingCurrentStatus
   * @example
   * // Get one ListingCurrentStatus
   * const listingCurrentStatus = await prisma.listingCurrentStatus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ListingCurrentStatusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ListingCurrentStatusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingCurrentStatus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingCurrentStatusFindFirstArgs} args - Arguments to find a ListingCurrentStatus
   * @example
   * // Get one ListingCurrentStatus
   * const listingCurrentStatus = await prisma.listingCurrentStatus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ListingCurrentStatusFindFirstArgs>(args?: Prisma.SelectSubset<T, ListingCurrentStatusFindFirstArgs<ExtArgs>>): Prisma.Prisma__ListingCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingCurrentStatus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingCurrentStatusFindFirstOrThrowArgs} args - Arguments to find a ListingCurrentStatus
   * @example
   * // Get one ListingCurrentStatus
   * const listingCurrentStatus = await prisma.listingCurrentStatus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ListingCurrentStatusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ListingCurrentStatusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ListingCurrentStatuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingCurrentStatusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ListingCurrentStatuses
   * const listingCurrentStatuses = await prisma.listingCurrentStatus.findMany()
   * 
   * // Get first 10 ListingCurrentStatuses
   * const listingCurrentStatuses = await prisma.listingCurrentStatus.findMany({ take: 10 })
   * 
   * // Only select the `listing_id`
   * const listingCurrentStatusWithListing_idOnly = await prisma.listingCurrentStatus.findMany({ select: { listing_id: true } })
   * 
   */
  findMany<T extends ListingCurrentStatusFindManyArgs>(args?: Prisma.SelectSubset<T, ListingCurrentStatusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ListingCurrentStatus.
   * @param {ListingCurrentStatusCreateArgs} args - Arguments to create a ListingCurrentStatus.
   * @example
   * // Create one ListingCurrentStatus
   * const ListingCurrentStatus = await prisma.listingCurrentStatus.create({
   *   data: {
   *     // ... data to create a ListingCurrentStatus
   *   }
   * })
   * 
   */
  create<T extends ListingCurrentStatusCreateArgs>(args: Prisma.SelectSubset<T, ListingCurrentStatusCreateArgs<ExtArgs>>): Prisma.Prisma__ListingCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ListingCurrentStatuses.
   * @param {ListingCurrentStatusCreateManyArgs} args - Arguments to create many ListingCurrentStatuses.
   * @example
   * // Create many ListingCurrentStatuses
   * const listingCurrentStatus = await prisma.listingCurrentStatus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ListingCurrentStatusCreateManyArgs>(args?: Prisma.SelectSubset<T, ListingCurrentStatusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ListingCurrentStatuses and returns the data saved in the database.
   * @param {ListingCurrentStatusCreateManyAndReturnArgs} args - Arguments to create many ListingCurrentStatuses.
   * @example
   * // Create many ListingCurrentStatuses
   * const listingCurrentStatus = await prisma.listingCurrentStatus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ListingCurrentStatuses and only return the `listing_id`
   * const listingCurrentStatusWithListing_idOnly = await prisma.listingCurrentStatus.createManyAndReturn({
   *   select: { listing_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ListingCurrentStatusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ListingCurrentStatusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ListingCurrentStatus.
   * @param {ListingCurrentStatusDeleteArgs} args - Arguments to delete one ListingCurrentStatus.
   * @example
   * // Delete one ListingCurrentStatus
   * const ListingCurrentStatus = await prisma.listingCurrentStatus.delete({
   *   where: {
   *     // ... filter to delete one ListingCurrentStatus
   *   }
   * })
   * 
   */
  delete<T extends ListingCurrentStatusDeleteArgs>(args: Prisma.SelectSubset<T, ListingCurrentStatusDeleteArgs<ExtArgs>>): Prisma.Prisma__ListingCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ListingCurrentStatus.
   * @param {ListingCurrentStatusUpdateArgs} args - Arguments to update one ListingCurrentStatus.
   * @example
   * // Update one ListingCurrentStatus
   * const listingCurrentStatus = await prisma.listingCurrentStatus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ListingCurrentStatusUpdateArgs>(args: Prisma.SelectSubset<T, ListingCurrentStatusUpdateArgs<ExtArgs>>): Prisma.Prisma__ListingCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ListingCurrentStatuses.
   * @param {ListingCurrentStatusDeleteManyArgs} args - Arguments to filter ListingCurrentStatuses to delete.
   * @example
   * // Delete a few ListingCurrentStatuses
   * const { count } = await prisma.listingCurrentStatus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ListingCurrentStatusDeleteManyArgs>(args?: Prisma.SelectSubset<T, ListingCurrentStatusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingCurrentStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingCurrentStatusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ListingCurrentStatuses
   * const listingCurrentStatus = await prisma.listingCurrentStatus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ListingCurrentStatusUpdateManyArgs>(args: Prisma.SelectSubset<T, ListingCurrentStatusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingCurrentStatuses and returns the data updated in the database.
   * @param {ListingCurrentStatusUpdateManyAndReturnArgs} args - Arguments to update many ListingCurrentStatuses.
   * @example
   * // Update many ListingCurrentStatuses
   * const listingCurrentStatus = await prisma.listingCurrentStatus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ListingCurrentStatuses and only return the `listing_id`
   * const listingCurrentStatusWithListing_idOnly = await prisma.listingCurrentStatus.updateManyAndReturn({
   *   select: { listing_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ListingCurrentStatusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ListingCurrentStatusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ListingCurrentStatus.
   * @param {ListingCurrentStatusUpsertArgs} args - Arguments to update or create a ListingCurrentStatus.
   * @example
   * // Update or create a ListingCurrentStatus
   * const listingCurrentStatus = await prisma.listingCurrentStatus.upsert({
   *   create: {
   *     // ... data to create a ListingCurrentStatus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ListingCurrentStatus we want to update
   *   }
   * })
   */
  upsert<T extends ListingCurrentStatusUpsertArgs>(args: Prisma.SelectSubset<T, ListingCurrentStatusUpsertArgs<ExtArgs>>): Prisma.Prisma__ListingCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ListingCurrentStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingCurrentStatusCountArgs} args - Arguments to filter ListingCurrentStatuses to count.
   * @example
   * // Count the number of ListingCurrentStatuses
   * const count = await prisma.listingCurrentStatus.count({
   *   where: {
   *     // ... the filter for the ListingCurrentStatuses we want to count
   *   }
   * })
  **/
  count<T extends ListingCurrentStatusCountArgs>(
    args?: Prisma.Subset<T, ListingCurrentStatusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ListingCurrentStatusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ListingCurrentStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingCurrentStatusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ListingCurrentStatusAggregateArgs>(args: Prisma.Subset<T, ListingCurrentStatusAggregateArgs>): Prisma.PrismaPromise<GetListingCurrentStatusAggregateType<T>>

  /**
   * Group by ListingCurrentStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingCurrentStatusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ListingCurrentStatusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ListingCurrentStatusGroupByArgs['orderBy'] }
      : { orderBy?: ListingCurrentStatusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ListingCurrentStatusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetListingCurrentStatusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ListingCurrentStatus model
 */
readonly fields: ListingCurrentStatusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ListingCurrentStatus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ListingCurrentStatusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  history<T extends Prisma.ListingStatusHistoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListingStatusHistoryDefaultArgs<ExtArgs>>): Prisma.Prisma__ListingStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  status<T extends Prisma.ListingStatusDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListingStatusDefaultArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ListingCurrentStatus model
 */
export interface ListingCurrentStatusFieldRefs {
  readonly listing_id: Prisma.FieldRef<"ListingCurrentStatus", 'String'>
  readonly listing_status_history_id: Prisma.FieldRef<"ListingCurrentStatus", 'String'>
  readonly listing_status_id: Prisma.FieldRef<"ListingCurrentStatus", 'String'>
  readonly deleted_at: Prisma.FieldRef<"ListingCurrentStatus", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ListingCurrentStatus findUnique
 */
export type ListingCurrentStatusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingCurrentStatus to fetch.
   */
  where: Prisma.ListingCurrentStatusWhereUniqueInput
}

/**
 * ListingCurrentStatus findUniqueOrThrow
 */
export type ListingCurrentStatusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingCurrentStatus to fetch.
   */
  where: Prisma.ListingCurrentStatusWhereUniqueInput
}

/**
 * ListingCurrentStatus findFirst
 */
export type ListingCurrentStatusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingCurrentStatus to fetch.
   */
  where?: Prisma.ListingCurrentStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingCurrentStatuses to fetch.
   */
  orderBy?: Prisma.ListingCurrentStatusOrderByWithRelationInput | Prisma.ListingCurrentStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingCurrentStatuses.
   */
  cursor?: Prisma.ListingCurrentStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingCurrentStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingCurrentStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingCurrentStatuses.
   */
  distinct?: Prisma.ListingCurrentStatusScalarFieldEnum | Prisma.ListingCurrentStatusScalarFieldEnum[]
}

/**
 * ListingCurrentStatus findFirstOrThrow
 */
export type ListingCurrentStatusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingCurrentStatus to fetch.
   */
  where?: Prisma.ListingCurrentStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingCurrentStatuses to fetch.
   */
  orderBy?: Prisma.ListingCurrentStatusOrderByWithRelationInput | Prisma.ListingCurrentStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingCurrentStatuses.
   */
  cursor?: Prisma.ListingCurrentStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingCurrentStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingCurrentStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingCurrentStatuses.
   */
  distinct?: Prisma.ListingCurrentStatusScalarFieldEnum | Prisma.ListingCurrentStatusScalarFieldEnum[]
}

/**
 * ListingCurrentStatus findMany
 */
export type ListingCurrentStatusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingCurrentStatuses to fetch.
   */
  where?: Prisma.ListingCurrentStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingCurrentStatuses to fetch.
   */
  orderBy?: Prisma.ListingCurrentStatusOrderByWithRelationInput | Prisma.ListingCurrentStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ListingCurrentStatuses.
   */
  cursor?: Prisma.ListingCurrentStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingCurrentStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingCurrentStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingCurrentStatuses.
   */
  distinct?: Prisma.ListingCurrentStatusScalarFieldEnum | Prisma.ListingCurrentStatusScalarFieldEnum[]
}

/**
 * ListingCurrentStatus create
 */
export type ListingCurrentStatusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  /**
   * The data needed to create a ListingCurrentStatus.
   */
  data: Prisma.XOR<Prisma.ListingCurrentStatusCreateInput, Prisma.ListingCurrentStatusUncheckedCreateInput>
}

/**
 * ListingCurrentStatus createMany
 */
export type ListingCurrentStatusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ListingCurrentStatuses.
   */
  data: Prisma.ListingCurrentStatusCreateManyInput | Prisma.ListingCurrentStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ListingCurrentStatus createManyAndReturn
 */
export type ListingCurrentStatusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * The data used to create many ListingCurrentStatuses.
   */
  data: Prisma.ListingCurrentStatusCreateManyInput | Prisma.ListingCurrentStatusCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ListingCurrentStatus update
 */
export type ListingCurrentStatusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  /**
   * The data needed to update a ListingCurrentStatus.
   */
  data: Prisma.XOR<Prisma.ListingCurrentStatusUpdateInput, Prisma.ListingCurrentStatusUncheckedUpdateInput>
  /**
   * Choose, which ListingCurrentStatus to update.
   */
  where: Prisma.ListingCurrentStatusWhereUniqueInput
}

/**
 * ListingCurrentStatus updateMany
 */
export type ListingCurrentStatusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ListingCurrentStatuses.
   */
  data: Prisma.XOR<Prisma.ListingCurrentStatusUpdateManyMutationInput, Prisma.ListingCurrentStatusUncheckedUpdateManyInput>
  /**
   * Filter which ListingCurrentStatuses to update
   */
  where?: Prisma.ListingCurrentStatusWhereInput
  /**
   * Limit how many ListingCurrentStatuses to update.
   */
  limit?: number
}

/**
 * ListingCurrentStatus updateManyAndReturn
 */
export type ListingCurrentStatusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * The data used to update ListingCurrentStatuses.
   */
  data: Prisma.XOR<Prisma.ListingCurrentStatusUpdateManyMutationInput, Prisma.ListingCurrentStatusUncheckedUpdateManyInput>
  /**
   * Filter which ListingCurrentStatuses to update
   */
  where?: Prisma.ListingCurrentStatusWhereInput
  /**
   * Limit how many ListingCurrentStatuses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ListingCurrentStatus upsert
 */
export type ListingCurrentStatusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  /**
   * The filter to search for the ListingCurrentStatus to update in case it exists.
   */
  where: Prisma.ListingCurrentStatusWhereUniqueInput
  /**
   * In case the ListingCurrentStatus found by the `where` argument doesn't exist, create a new ListingCurrentStatus with this data.
   */
  create: Prisma.XOR<Prisma.ListingCurrentStatusCreateInput, Prisma.ListingCurrentStatusUncheckedCreateInput>
  /**
   * In case the ListingCurrentStatus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ListingCurrentStatusUpdateInput, Prisma.ListingCurrentStatusUncheckedUpdateInput>
}

/**
 * ListingCurrentStatus delete
 */
export type ListingCurrentStatusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  /**
   * Filter which ListingCurrentStatus to delete.
   */
  where: Prisma.ListingCurrentStatusWhereUniqueInput
}

/**
 * ListingCurrentStatus deleteMany
 */
export type ListingCurrentStatusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingCurrentStatuses to delete
   */
  where?: Prisma.ListingCurrentStatusWhereInput
  /**
   * Limit how many ListingCurrentStatuses to delete.
   */
  limit?: number
}

/**
 * ListingCurrentStatus without action
 */
export type ListingCurrentStatusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
}
