
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ListingStatusHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ListingStatusHistory
 * 
 */
export type ListingStatusHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$ListingStatusHistoryPayload>

export type AggregateListingStatusHistory = {
  _count: ListingStatusHistoryCountAggregateOutputType | null
  _min: ListingStatusHistoryMinAggregateOutputType | null
  _max: ListingStatusHistoryMaxAggregateOutputType | null
}

export type ListingStatusHistoryMinAggregateOutputType = {
  id: string | null
  listing_id: string | null
  listing_status_id: string | null
  record_created_at: Date | null
  deleted_at: Date | null
}

export type ListingStatusHistoryMaxAggregateOutputType = {
  id: string | null
  listing_id: string | null
  listing_status_id: string | null
  record_created_at: Date | null
  deleted_at: Date | null
}

export type ListingStatusHistoryCountAggregateOutputType = {
  id: number
  listing_id: number
  listing_status_id: number
  record_created_at: number
  deleted_at: number
  _all: number
}


export type ListingStatusHistoryMinAggregateInputType = {
  id?: true
  listing_id?: true
  listing_status_id?: true
  record_created_at?: true
  deleted_at?: true
}

export type ListingStatusHistoryMaxAggregateInputType = {
  id?: true
  listing_id?: true
  listing_status_id?: true
  record_created_at?: true
  deleted_at?: true
}

export type ListingStatusHistoryCountAggregateInputType = {
  id?: true
  listing_id?: true
  listing_status_id?: true
  record_created_at?: true
  deleted_at?: true
  _all?: true
}

export type ListingStatusHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingStatusHistory to aggregate.
   */
  where?: Prisma.ListingStatusHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingStatusHistories to fetch.
   */
  orderBy?: Prisma.ListingStatusHistoryOrderByWithRelationInput | Prisma.ListingStatusHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ListingStatusHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingStatusHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingStatusHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ListingStatusHistories
  **/
  _count?: true | ListingStatusHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ListingStatusHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ListingStatusHistoryMaxAggregateInputType
}

export type GetListingStatusHistoryAggregateType<T extends ListingStatusHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateListingStatusHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateListingStatusHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateListingStatusHistory[P]>
}




export type ListingStatusHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingStatusHistoryWhereInput
  orderBy?: Prisma.ListingStatusHistoryOrderByWithAggregationInput | Prisma.ListingStatusHistoryOrderByWithAggregationInput[]
  by: Prisma.ListingStatusHistoryScalarFieldEnum[] | Prisma.ListingStatusHistoryScalarFieldEnum
  having?: Prisma.ListingStatusHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ListingStatusHistoryCountAggregateInputType | true
  _min?: ListingStatusHistoryMinAggregateInputType
  _max?: ListingStatusHistoryMaxAggregateInputType
}

export type ListingStatusHistoryGroupByOutputType = {
  id: string
  listing_id: string
  listing_status_id: string
  record_created_at: Date
  deleted_at: Date | null
  _count: ListingStatusHistoryCountAggregateOutputType | null
  _min: ListingStatusHistoryMinAggregateOutputType | null
  _max: ListingStatusHistoryMaxAggregateOutputType | null
}

export type GetListingStatusHistoryGroupByPayload<T extends ListingStatusHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ListingStatusHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ListingStatusHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ListingStatusHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ListingStatusHistoryGroupByOutputType[P]>
      }
    >
  >



export type ListingStatusHistoryWhereInput = {
  AND?: Prisma.ListingStatusHistoryWhereInput | Prisma.ListingStatusHistoryWhereInput[]
  OR?: Prisma.ListingStatusHistoryWhereInput[]
  NOT?: Prisma.ListingStatusHistoryWhereInput | Prisma.ListingStatusHistoryWhereInput[]
  id?: Prisma.StringFilter<"ListingStatusHistory"> | string
  listing_id?: Prisma.StringFilter<"ListingStatusHistory"> | string
  listing_status_id?: Prisma.StringFilter<"ListingStatusHistory"> | string
  record_created_at?: Prisma.DateTimeFilter<"ListingStatusHistory"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"ListingStatusHistory"> | Date | string | null
  status?: Prisma.XOR<Prisma.ListingStatusScalarRelationFilter, Prisma.ListingStatusWhereInput>
  current?: Prisma.XOR<Prisma.ListingCurrentStatusNullableScalarRelationFilter, Prisma.ListingCurrentStatusWhereInput> | null
}

export type ListingStatusHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  listing_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  record_created_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.ListingStatusOrderByWithRelationInput
  current?: Prisma.ListingCurrentStatusOrderByWithRelationInput
}

export type ListingStatusHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ListingStatusHistoryWhereInput | Prisma.ListingStatusHistoryWhereInput[]
  OR?: Prisma.ListingStatusHistoryWhereInput[]
  NOT?: Prisma.ListingStatusHistoryWhereInput | Prisma.ListingStatusHistoryWhereInput[]
  listing_id?: Prisma.StringFilter<"ListingStatusHistory"> | string
  listing_status_id?: Prisma.StringFilter<"ListingStatusHistory"> | string
  record_created_at?: Prisma.DateTimeFilter<"ListingStatusHistory"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"ListingStatusHistory"> | Date | string | null
  status?: Prisma.XOR<Prisma.ListingStatusScalarRelationFilter, Prisma.ListingStatusWhereInput>
  current?: Prisma.XOR<Prisma.ListingCurrentStatusNullableScalarRelationFilter, Prisma.ListingCurrentStatusWhereInput> | null
}, "id">

export type ListingStatusHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  listing_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  record_created_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ListingStatusHistoryCountOrderByAggregateInput
  _max?: Prisma.ListingStatusHistoryMaxOrderByAggregateInput
  _min?: Prisma.ListingStatusHistoryMinOrderByAggregateInput
}

export type ListingStatusHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.ListingStatusHistoryScalarWhereWithAggregatesInput | Prisma.ListingStatusHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.ListingStatusHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ListingStatusHistoryScalarWhereWithAggregatesInput | Prisma.ListingStatusHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ListingStatusHistory"> | string
  listing_id?: Prisma.StringWithAggregatesFilter<"ListingStatusHistory"> | string
  listing_status_id?: Prisma.StringWithAggregatesFilter<"ListingStatusHistory"> | string
  record_created_at?: Prisma.DateTimeWithAggregatesFilter<"ListingStatusHistory"> | Date | string
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"ListingStatusHistory"> | Date | string | null
}

export type ListingStatusHistoryCreateInput = {
  id?: string
  listing_id: string
  record_created_at?: Date | string
  deleted_at?: Date | string | null
  status: Prisma.ListingStatusCreateNestedOneWithoutHistoryInput
  current?: Prisma.ListingCurrentStatusCreateNestedOneWithoutHistoryInput
}

export type ListingStatusHistoryUncheckedCreateInput = {
  id?: string
  listing_id: string
  listing_status_id: string
  record_created_at?: Date | string
  deleted_at?: Date | string | null
  current?: Prisma.ListingCurrentStatusUncheckedCreateNestedOneWithoutHistoryInput
}

export type ListingStatusHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  record_created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.ListingStatusUpdateOneRequiredWithoutHistoryNestedInput
  current?: Prisma.ListingCurrentStatusUpdateOneWithoutHistoryNestedInput
}

export type ListingStatusHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_id?: Prisma.StringFieldUpdateOperationsInput | string
  record_created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  current?: Prisma.ListingCurrentStatusUncheckedUpdateOneWithoutHistoryNestedInput
}

export type ListingStatusHistoryCreateManyInput = {
  id?: string
  listing_id: string
  listing_status_id: string
  record_created_at?: Date | string
  deleted_at?: Date | string | null
}

export type ListingStatusHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  record_created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ListingStatusHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_id?: Prisma.StringFieldUpdateOperationsInput | string
  record_created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ListingStatusHistoryListRelationFilter = {
  every?: Prisma.ListingStatusHistoryWhereInput
  some?: Prisma.ListingStatusHistoryWhereInput
  none?: Prisma.ListingStatusHistoryWhereInput
}

export type ListingStatusHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ListingStatusHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  listing_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  record_created_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type ListingStatusHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  listing_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  record_created_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type ListingStatusHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  listing_id?: Prisma.SortOrder
  listing_status_id?: Prisma.SortOrder
  record_created_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type ListingStatusHistoryScalarRelationFilter = {
  is?: Prisma.ListingStatusHistoryWhereInput
  isNot?: Prisma.ListingStatusHistoryWhereInput
}

export type ListingStatusHistoryCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutStatusInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput> | Prisma.ListingStatusHistoryCreateWithoutStatusInput[] | Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.ListingStatusHistoryCreateOrConnectWithoutStatusInput | Prisma.ListingStatusHistoryCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.ListingStatusHistoryCreateManyStatusInputEnvelope
  connect?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
}

export type ListingStatusHistoryUncheckedCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutStatusInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput> | Prisma.ListingStatusHistoryCreateWithoutStatusInput[] | Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.ListingStatusHistoryCreateOrConnectWithoutStatusInput | Prisma.ListingStatusHistoryCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.ListingStatusHistoryCreateManyStatusInputEnvelope
  connect?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
}

export type ListingStatusHistoryUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutStatusInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput> | Prisma.ListingStatusHistoryCreateWithoutStatusInput[] | Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.ListingStatusHistoryCreateOrConnectWithoutStatusInput | Prisma.ListingStatusHistoryCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.ListingStatusHistoryUpsertWithWhereUniqueWithoutStatusInput | Prisma.ListingStatusHistoryUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.ListingStatusHistoryCreateManyStatusInputEnvelope
  set?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
  disconnect?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
  delete?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
  connect?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
  update?: Prisma.ListingStatusHistoryUpdateWithWhereUniqueWithoutStatusInput | Prisma.ListingStatusHistoryUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.ListingStatusHistoryUpdateManyWithWhereWithoutStatusInput | Prisma.ListingStatusHistoryUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.ListingStatusHistoryScalarWhereInput | Prisma.ListingStatusHistoryScalarWhereInput[]
}

export type ListingStatusHistoryUncheckedUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutStatusInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput> | Prisma.ListingStatusHistoryCreateWithoutStatusInput[] | Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.ListingStatusHistoryCreateOrConnectWithoutStatusInput | Prisma.ListingStatusHistoryCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.ListingStatusHistoryUpsertWithWhereUniqueWithoutStatusInput | Prisma.ListingStatusHistoryUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.ListingStatusHistoryCreateManyStatusInputEnvelope
  set?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
  disconnect?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
  delete?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
  connect?: Prisma.ListingStatusHistoryWhereUniqueInput | Prisma.ListingStatusHistoryWhereUniqueInput[]
  update?: Prisma.ListingStatusHistoryUpdateWithWhereUniqueWithoutStatusInput | Prisma.ListingStatusHistoryUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.ListingStatusHistoryUpdateManyWithWhereWithoutStatusInput | Prisma.ListingStatusHistoryUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.ListingStatusHistoryScalarWhereInput | Prisma.ListingStatusHistoryScalarWhereInput[]
}

export type ListingStatusHistoryCreateNestedOneWithoutCurrentInput = {
  create?: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutCurrentInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutCurrentInput>
  connectOrCreate?: Prisma.ListingStatusHistoryCreateOrConnectWithoutCurrentInput
  connect?: Prisma.ListingStatusHistoryWhereUniqueInput
}

export type ListingStatusHistoryUpdateOneRequiredWithoutCurrentNestedInput = {
  create?: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutCurrentInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutCurrentInput>
  connectOrCreate?: Prisma.ListingStatusHistoryCreateOrConnectWithoutCurrentInput
  upsert?: Prisma.ListingStatusHistoryUpsertWithoutCurrentInput
  connect?: Prisma.ListingStatusHistoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListingStatusHistoryUpdateToOneWithWhereWithoutCurrentInput, Prisma.ListingStatusHistoryUpdateWithoutCurrentInput>, Prisma.ListingStatusHistoryUncheckedUpdateWithoutCurrentInput>
}

export type ListingStatusHistoryCreateWithoutStatusInput = {
  id?: string
  listing_id: string
  record_created_at?: Date | string
  deleted_at?: Date | string | null
  current?: Prisma.ListingCurrentStatusCreateNestedOneWithoutHistoryInput
}

export type ListingStatusHistoryUncheckedCreateWithoutStatusInput = {
  id?: string
  listing_id: string
  record_created_at?: Date | string
  deleted_at?: Date | string | null
  current?: Prisma.ListingCurrentStatusUncheckedCreateNestedOneWithoutHistoryInput
}

export type ListingStatusHistoryCreateOrConnectWithoutStatusInput = {
  where: Prisma.ListingStatusHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutStatusInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput>
}

export type ListingStatusHistoryCreateManyStatusInputEnvelope = {
  data: Prisma.ListingStatusHistoryCreateManyStatusInput | Prisma.ListingStatusHistoryCreateManyStatusInput[]
  skipDuplicates?: boolean
}

export type ListingStatusHistoryUpsertWithWhereUniqueWithoutStatusInput = {
  where: Prisma.ListingStatusHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ListingStatusHistoryUpdateWithoutStatusInput, Prisma.ListingStatusHistoryUncheckedUpdateWithoutStatusInput>
  create: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutStatusInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutStatusInput>
}

export type ListingStatusHistoryUpdateWithWhereUniqueWithoutStatusInput = {
  where: Prisma.ListingStatusHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ListingStatusHistoryUpdateWithoutStatusInput, Prisma.ListingStatusHistoryUncheckedUpdateWithoutStatusInput>
}

export type ListingStatusHistoryUpdateManyWithWhereWithoutStatusInput = {
  where: Prisma.ListingStatusHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.ListingStatusHistoryUpdateManyMutationInput, Prisma.ListingStatusHistoryUncheckedUpdateManyWithoutStatusInput>
}

export type ListingStatusHistoryScalarWhereInput = {
  AND?: Prisma.ListingStatusHistoryScalarWhereInput | Prisma.ListingStatusHistoryScalarWhereInput[]
  OR?: Prisma.ListingStatusHistoryScalarWhereInput[]
  NOT?: Prisma.ListingStatusHistoryScalarWhereInput | Prisma.ListingStatusHistoryScalarWhereInput[]
  id?: Prisma.StringFilter<"ListingStatusHistory"> | string
  listing_id?: Prisma.StringFilter<"ListingStatusHistory"> | string
  listing_status_id?: Prisma.StringFilter<"ListingStatusHistory"> | string
  record_created_at?: Prisma.DateTimeFilter<"ListingStatusHistory"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"ListingStatusHistory"> | Date | string | null
}

export type ListingStatusHistoryCreateWithoutCurrentInput = {
  id?: string
  listing_id: string
  record_created_at?: Date | string
  deleted_at?: Date | string | null
  status: Prisma.ListingStatusCreateNestedOneWithoutHistoryInput
}

export type ListingStatusHistoryUncheckedCreateWithoutCurrentInput = {
  id?: string
  listing_id: string
  listing_status_id: string
  record_created_at?: Date | string
  deleted_at?: Date | string | null
}

export type ListingStatusHistoryCreateOrConnectWithoutCurrentInput = {
  where: Prisma.ListingStatusHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutCurrentInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutCurrentInput>
}

export type ListingStatusHistoryUpsertWithoutCurrentInput = {
  update: Prisma.XOR<Prisma.ListingStatusHistoryUpdateWithoutCurrentInput, Prisma.ListingStatusHistoryUncheckedUpdateWithoutCurrentInput>
  create: Prisma.XOR<Prisma.ListingStatusHistoryCreateWithoutCurrentInput, Prisma.ListingStatusHistoryUncheckedCreateWithoutCurrentInput>
  where?: Prisma.ListingStatusHistoryWhereInput
}

export type ListingStatusHistoryUpdateToOneWithWhereWithoutCurrentInput = {
  where?: Prisma.ListingStatusHistoryWhereInput
  data: Prisma.XOR<Prisma.ListingStatusHistoryUpdateWithoutCurrentInput, Prisma.ListingStatusHistoryUncheckedUpdateWithoutCurrentInput>
}

export type ListingStatusHistoryUpdateWithoutCurrentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  record_created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.ListingStatusUpdateOneRequiredWithoutHistoryNestedInput
}

export type ListingStatusHistoryUncheckedUpdateWithoutCurrentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_status_id?: Prisma.StringFieldUpdateOperationsInput | string
  record_created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ListingStatusHistoryCreateManyStatusInput = {
  id?: string
  listing_id: string
  record_created_at?: Date | string
  deleted_at?: Date | string | null
}

export type ListingStatusHistoryUpdateWithoutStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  record_created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  current?: Prisma.ListingCurrentStatusUpdateOneWithoutHistoryNestedInput
}

export type ListingStatusHistoryUncheckedUpdateWithoutStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  record_created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  current?: Prisma.ListingCurrentStatusUncheckedUpdateOneWithoutHistoryNestedInput
}

export type ListingStatusHistoryUncheckedUpdateManyWithoutStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listing_id?: Prisma.StringFieldUpdateOperationsInput | string
  record_created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type ListingStatusHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  listing_id?: boolean
  listing_status_id?: boolean
  record_created_at?: boolean
  deleted_at?: boolean
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
  current?: boolean | Prisma.ListingStatusHistory$currentArgs<ExtArgs>
}, ExtArgs["result"]["listingStatusHistory"]>

export type ListingStatusHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  listing_id?: boolean
  listing_status_id?: boolean
  record_created_at?: boolean
  deleted_at?: boolean
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingStatusHistory"]>

export type ListingStatusHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  listing_id?: boolean
  listing_status_id?: boolean
  record_created_at?: boolean
  deleted_at?: boolean
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingStatusHistory"]>

export type ListingStatusHistorySelectScalar = {
  id?: boolean
  listing_id?: boolean
  listing_status_id?: boolean
  record_created_at?: boolean
  deleted_at?: boolean
}

export type ListingStatusHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "listing_id" | "listing_status_id" | "record_created_at" | "deleted_at", ExtArgs["result"]["listingStatusHistory"]>
export type ListingStatusHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
  current?: boolean | Prisma.ListingStatusHistory$currentArgs<ExtArgs>
}
export type ListingStatusHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}
export type ListingStatusHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  status?: boolean | Prisma.ListingStatusDefaultArgs<ExtArgs>
}

export type $ListingStatusHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ListingStatusHistory"
  objects: {
    status: Prisma.$ListingStatusPayload<ExtArgs>
    current: Prisma.$ListingCurrentStatusPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    listing_id: string
    listing_status_id: string
    record_created_at: Date
    deleted_at: Date | null
  }, ExtArgs["result"]["listingStatusHistory"]>
  composites: {}
}

export type ListingStatusHistoryGetPayload<S extends boolean | null | undefined | ListingStatusHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload, S>

export type ListingStatusHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ListingStatusHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ListingStatusHistoryCountAggregateInputType | true
  }

export interface ListingStatusHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ListingStatusHistory'], meta: { name: 'ListingStatusHistory' } }
  /**
   * Find zero or one ListingStatusHistory that matches the filter.
   * @param {ListingStatusHistoryFindUniqueArgs} args - Arguments to find a ListingStatusHistory
   * @example
   * // Get one ListingStatusHistory
   * const listingStatusHistory = await prisma.listingStatusHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ListingStatusHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, ListingStatusHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ListingStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ListingStatusHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ListingStatusHistoryFindUniqueOrThrowArgs} args - Arguments to find a ListingStatusHistory
   * @example
   * // Get one ListingStatusHistory
   * const listingStatusHistory = await prisma.listingStatusHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ListingStatusHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ListingStatusHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingStatusHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusHistoryFindFirstArgs} args - Arguments to find a ListingStatusHistory
   * @example
   * // Get one ListingStatusHistory
   * const listingStatusHistory = await prisma.listingStatusHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ListingStatusHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, ListingStatusHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__ListingStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingStatusHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusHistoryFindFirstOrThrowArgs} args - Arguments to find a ListingStatusHistory
   * @example
   * // Get one ListingStatusHistory
   * const listingStatusHistory = await prisma.listingStatusHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ListingStatusHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ListingStatusHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ListingStatusHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ListingStatusHistories
   * const listingStatusHistories = await prisma.listingStatusHistory.findMany()
   * 
   * // Get first 10 ListingStatusHistories
   * const listingStatusHistories = await prisma.listingStatusHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const listingStatusHistoryWithIdOnly = await prisma.listingStatusHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ListingStatusHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, ListingStatusHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ListingStatusHistory.
   * @param {ListingStatusHistoryCreateArgs} args - Arguments to create a ListingStatusHistory.
   * @example
   * // Create one ListingStatusHistory
   * const ListingStatusHistory = await prisma.listingStatusHistory.create({
   *   data: {
   *     // ... data to create a ListingStatusHistory
   *   }
   * })
   * 
   */
  create<T extends ListingStatusHistoryCreateArgs>(args: Prisma.SelectSubset<T, ListingStatusHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__ListingStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ListingStatusHistories.
   * @param {ListingStatusHistoryCreateManyArgs} args - Arguments to create many ListingStatusHistories.
   * @example
   * // Create many ListingStatusHistories
   * const listingStatusHistory = await prisma.listingStatusHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ListingStatusHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, ListingStatusHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ListingStatusHistories and returns the data saved in the database.
   * @param {ListingStatusHistoryCreateManyAndReturnArgs} args - Arguments to create many ListingStatusHistories.
   * @example
   * // Create many ListingStatusHistories
   * const listingStatusHistory = await prisma.listingStatusHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ListingStatusHistories and only return the `id`
   * const listingStatusHistoryWithIdOnly = await prisma.listingStatusHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ListingStatusHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ListingStatusHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ListingStatusHistory.
   * @param {ListingStatusHistoryDeleteArgs} args - Arguments to delete one ListingStatusHistory.
   * @example
   * // Delete one ListingStatusHistory
   * const ListingStatusHistory = await prisma.listingStatusHistory.delete({
   *   where: {
   *     // ... filter to delete one ListingStatusHistory
   *   }
   * })
   * 
   */
  delete<T extends ListingStatusHistoryDeleteArgs>(args: Prisma.SelectSubset<T, ListingStatusHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__ListingStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ListingStatusHistory.
   * @param {ListingStatusHistoryUpdateArgs} args - Arguments to update one ListingStatusHistory.
   * @example
   * // Update one ListingStatusHistory
   * const listingStatusHistory = await prisma.listingStatusHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ListingStatusHistoryUpdateArgs>(args: Prisma.SelectSubset<T, ListingStatusHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__ListingStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ListingStatusHistories.
   * @param {ListingStatusHistoryDeleteManyArgs} args - Arguments to filter ListingStatusHistories to delete.
   * @example
   * // Delete a few ListingStatusHistories
   * const { count } = await prisma.listingStatusHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ListingStatusHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, ListingStatusHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingStatusHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ListingStatusHistories
   * const listingStatusHistory = await prisma.listingStatusHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ListingStatusHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, ListingStatusHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingStatusHistories and returns the data updated in the database.
   * @param {ListingStatusHistoryUpdateManyAndReturnArgs} args - Arguments to update many ListingStatusHistories.
   * @example
   * // Update many ListingStatusHistories
   * const listingStatusHistory = await prisma.listingStatusHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ListingStatusHistories and only return the `id`
   * const listingStatusHistoryWithIdOnly = await prisma.listingStatusHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ListingStatusHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ListingStatusHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ListingStatusHistory.
   * @param {ListingStatusHistoryUpsertArgs} args - Arguments to update or create a ListingStatusHistory.
   * @example
   * // Update or create a ListingStatusHistory
   * const listingStatusHistory = await prisma.listingStatusHistory.upsert({
   *   create: {
   *     // ... data to create a ListingStatusHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ListingStatusHistory we want to update
   *   }
   * })
   */
  upsert<T extends ListingStatusHistoryUpsertArgs>(args: Prisma.SelectSubset<T, ListingStatusHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__ListingStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ListingStatusHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusHistoryCountArgs} args - Arguments to filter ListingStatusHistories to count.
   * @example
   * // Count the number of ListingStatusHistories
   * const count = await prisma.listingStatusHistory.count({
   *   where: {
   *     // ... the filter for the ListingStatusHistories we want to count
   *   }
   * })
  **/
  count<T extends ListingStatusHistoryCountArgs>(
    args?: Prisma.Subset<T, ListingStatusHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ListingStatusHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ListingStatusHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ListingStatusHistoryAggregateArgs>(args: Prisma.Subset<T, ListingStatusHistoryAggregateArgs>): Prisma.PrismaPromise<GetListingStatusHistoryAggregateType<T>>

  /**
   * Group by ListingStatusHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ListingStatusHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ListingStatusHistoryGroupByArgs['orderBy'] }
      : { orderBy?: ListingStatusHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ListingStatusHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetListingStatusHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ListingStatusHistory model
 */
readonly fields: ListingStatusHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ListingStatusHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ListingStatusHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  status<T extends Prisma.ListingStatusDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListingStatusDefaultArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  current<T extends Prisma.ListingStatusHistory$currentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListingStatusHistory$currentArgs<ExtArgs>>): Prisma.Prisma__ListingCurrentStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ListingStatusHistory model
 */
export interface ListingStatusHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"ListingStatusHistory", 'String'>
  readonly listing_id: Prisma.FieldRef<"ListingStatusHistory", 'String'>
  readonly listing_status_id: Prisma.FieldRef<"ListingStatusHistory", 'String'>
  readonly record_created_at: Prisma.FieldRef<"ListingStatusHistory", 'DateTime'>
  readonly deleted_at: Prisma.FieldRef<"ListingStatusHistory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ListingStatusHistory findUnique
 */
export type ListingStatusHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatusHistory to fetch.
   */
  where: Prisma.ListingStatusHistoryWhereUniqueInput
}

/**
 * ListingStatusHistory findUniqueOrThrow
 */
export type ListingStatusHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatusHistory to fetch.
   */
  where: Prisma.ListingStatusHistoryWhereUniqueInput
}

/**
 * ListingStatusHistory findFirst
 */
export type ListingStatusHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatusHistory to fetch.
   */
  where?: Prisma.ListingStatusHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingStatusHistories to fetch.
   */
  orderBy?: Prisma.ListingStatusHistoryOrderByWithRelationInput | Prisma.ListingStatusHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingStatusHistories.
   */
  cursor?: Prisma.ListingStatusHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingStatusHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingStatusHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingStatusHistories.
   */
  distinct?: Prisma.ListingStatusHistoryScalarFieldEnum | Prisma.ListingStatusHistoryScalarFieldEnum[]
}

/**
 * ListingStatusHistory findFirstOrThrow
 */
export type ListingStatusHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatusHistory to fetch.
   */
  where?: Prisma.ListingStatusHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingStatusHistories to fetch.
   */
  orderBy?: Prisma.ListingStatusHistoryOrderByWithRelationInput | Prisma.ListingStatusHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingStatusHistories.
   */
  cursor?: Prisma.ListingStatusHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingStatusHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingStatusHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingStatusHistories.
   */
  distinct?: Prisma.ListingStatusHistoryScalarFieldEnum | Prisma.ListingStatusHistoryScalarFieldEnum[]
}

/**
 * ListingStatusHistory findMany
 */
export type ListingStatusHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatusHistories to fetch.
   */
  where?: Prisma.ListingStatusHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingStatusHistories to fetch.
   */
  orderBy?: Prisma.ListingStatusHistoryOrderByWithRelationInput | Prisma.ListingStatusHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ListingStatusHistories.
   */
  cursor?: Prisma.ListingStatusHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingStatusHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingStatusHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingStatusHistories.
   */
  distinct?: Prisma.ListingStatusHistoryScalarFieldEnum | Prisma.ListingStatusHistoryScalarFieldEnum[]
}

/**
 * ListingStatusHistory create
 */
export type ListingStatusHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a ListingStatusHistory.
   */
  data: Prisma.XOR<Prisma.ListingStatusHistoryCreateInput, Prisma.ListingStatusHistoryUncheckedCreateInput>
}

/**
 * ListingStatusHistory createMany
 */
export type ListingStatusHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ListingStatusHistories.
   */
  data: Prisma.ListingStatusHistoryCreateManyInput | Prisma.ListingStatusHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ListingStatusHistory createManyAndReturn
 */
export type ListingStatusHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many ListingStatusHistories.
   */
  data: Prisma.ListingStatusHistoryCreateManyInput | Prisma.ListingStatusHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ListingStatusHistory update
 */
export type ListingStatusHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a ListingStatusHistory.
   */
  data: Prisma.XOR<Prisma.ListingStatusHistoryUpdateInput, Prisma.ListingStatusHistoryUncheckedUpdateInput>
  /**
   * Choose, which ListingStatusHistory to update.
   */
  where: Prisma.ListingStatusHistoryWhereUniqueInput
}

/**
 * ListingStatusHistory updateMany
 */
export type ListingStatusHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ListingStatusHistories.
   */
  data: Prisma.XOR<Prisma.ListingStatusHistoryUpdateManyMutationInput, Prisma.ListingStatusHistoryUncheckedUpdateManyInput>
  /**
   * Filter which ListingStatusHistories to update
   */
  where?: Prisma.ListingStatusHistoryWhereInput
  /**
   * Limit how many ListingStatusHistories to update.
   */
  limit?: number
}

/**
 * ListingStatusHistory updateManyAndReturn
 */
export type ListingStatusHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * The data used to update ListingStatusHistories.
   */
  data: Prisma.XOR<Prisma.ListingStatusHistoryUpdateManyMutationInput, Prisma.ListingStatusHistoryUncheckedUpdateManyInput>
  /**
   * Filter which ListingStatusHistories to update
   */
  where?: Prisma.ListingStatusHistoryWhereInput
  /**
   * Limit how many ListingStatusHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ListingStatusHistory upsert
 */
export type ListingStatusHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the ListingStatusHistory to update in case it exists.
   */
  where: Prisma.ListingStatusHistoryWhereUniqueInput
  /**
   * In case the ListingStatusHistory found by the `where` argument doesn't exist, create a new ListingStatusHistory with this data.
   */
  create: Prisma.XOR<Prisma.ListingStatusHistoryCreateInput, Prisma.ListingStatusHistoryUncheckedCreateInput>
  /**
   * In case the ListingStatusHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ListingStatusHistoryUpdateInput, Prisma.ListingStatusHistoryUncheckedUpdateInput>
}

/**
 * ListingStatusHistory delete
 */
export type ListingStatusHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter which ListingStatusHistory to delete.
   */
  where: Prisma.ListingStatusHistoryWhereUniqueInput
}

/**
 * ListingStatusHistory deleteMany
 */
export type ListingStatusHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingStatusHistories to delete
   */
  where?: Prisma.ListingStatusHistoryWhereInput
  /**
   * Limit how many ListingStatusHistories to delete.
   */
  limit?: number
}

/**
 * ListingStatusHistory.current
 */
export type ListingStatusHistory$currentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  where?: Prisma.ListingCurrentStatusWhereInput
}

/**
 * ListingStatusHistory without action
 */
export type ListingStatusHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
}
