
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ListingStatus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ListingStatus
 * 
 */
export type ListingStatusModel = runtime.Types.Result.DefaultSelection<Prisma.$ListingStatusPayload>

export type AggregateListingStatus = {
  _count: ListingStatusCountAggregateOutputType | null
  _min: ListingStatusMinAggregateOutputType | null
  _max: ListingStatusMaxAggregateOutputType | null
}

export type ListingStatusMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
}

export type ListingStatusMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
}

export type ListingStatusCountAggregateOutputType = {
  id: number
  name: number
  description: number
  _all: number
}


export type ListingStatusMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
}

export type ListingStatusMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
}

export type ListingStatusCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  _all?: true
}

export type ListingStatusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingStatus to aggregate.
   */
  where?: Prisma.ListingStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingStatuses to fetch.
   */
  orderBy?: Prisma.ListingStatusOrderByWithRelationInput | Prisma.ListingStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ListingStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ListingStatuses
  **/
  _count?: true | ListingStatusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ListingStatusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ListingStatusMaxAggregateInputType
}

export type GetListingStatusAggregateType<T extends ListingStatusAggregateArgs> = {
      [P in keyof T & keyof AggregateListingStatus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateListingStatus[P]>
    : Prisma.GetScalarType<T[P], AggregateListingStatus[P]>
}




export type ListingStatusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingStatusWhereInput
  orderBy?: Prisma.ListingStatusOrderByWithAggregationInput | Prisma.ListingStatusOrderByWithAggregationInput[]
  by: Prisma.ListingStatusScalarFieldEnum[] | Prisma.ListingStatusScalarFieldEnum
  having?: Prisma.ListingStatusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ListingStatusCountAggregateInputType | true
  _min?: ListingStatusMinAggregateInputType
  _max?: ListingStatusMaxAggregateInputType
}

export type ListingStatusGroupByOutputType = {
  id: string
  name: string
  description: string | null
  _count: ListingStatusCountAggregateOutputType | null
  _min: ListingStatusMinAggregateOutputType | null
  _max: ListingStatusMaxAggregateOutputType | null
}

export type GetListingStatusGroupByPayload<T extends ListingStatusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ListingStatusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ListingStatusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ListingStatusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ListingStatusGroupByOutputType[P]>
      }
    >
  >



export type ListingStatusWhereInput = {
  AND?: Prisma.ListingStatusWhereInput | Prisma.ListingStatusWhereInput[]
  OR?: Prisma.ListingStatusWhereInput[]
  NOT?: Prisma.ListingStatusWhereInput | Prisma.ListingStatusWhereInput[]
  id?: Prisma.StringFilter<"ListingStatus"> | string
  name?: Prisma.StringFilter<"ListingStatus"> | string
  description?: Prisma.StringNullableFilter<"ListingStatus"> | string | null
  history?: Prisma.ListingStatusHistoryListRelationFilter
  current?: Prisma.ListingCurrentStatusListRelationFilter
}

export type ListingStatusOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  history?: Prisma.ListingStatusHistoryOrderByRelationAggregateInput
  current?: Prisma.ListingCurrentStatusOrderByRelationAggregateInput
}

export type ListingStatusWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.ListingStatusWhereInput | Prisma.ListingStatusWhereInput[]
  OR?: Prisma.ListingStatusWhereInput[]
  NOT?: Prisma.ListingStatusWhereInput | Prisma.ListingStatusWhereInput[]
  description?: Prisma.StringNullableFilter<"ListingStatus"> | string | null
  history?: Prisma.ListingStatusHistoryListRelationFilter
  current?: Prisma.ListingCurrentStatusListRelationFilter
}, "id" | "name">

export type ListingStatusOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ListingStatusCountOrderByAggregateInput
  _max?: Prisma.ListingStatusMaxOrderByAggregateInput
  _min?: Prisma.ListingStatusMinOrderByAggregateInput
}

export type ListingStatusScalarWhereWithAggregatesInput = {
  AND?: Prisma.ListingStatusScalarWhereWithAggregatesInput | Prisma.ListingStatusScalarWhereWithAggregatesInput[]
  OR?: Prisma.ListingStatusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ListingStatusScalarWhereWithAggregatesInput | Prisma.ListingStatusScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ListingStatus"> | string
  name?: Prisma.StringWithAggregatesFilter<"ListingStatus"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"ListingStatus"> | string | null
}

export type ListingStatusCreateInput = {
  id?: string
  name: string
  description?: string | null
  history?: Prisma.ListingStatusHistoryCreateNestedManyWithoutStatusInput
  current?: Prisma.ListingCurrentStatusCreateNestedManyWithoutStatusInput
}

export type ListingStatusUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  history?: Prisma.ListingStatusHistoryUncheckedCreateNestedManyWithoutStatusInput
  current?: Prisma.ListingCurrentStatusUncheckedCreateNestedManyWithoutStatusInput
}

export type ListingStatusUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.ListingStatusHistoryUpdateManyWithoutStatusNestedInput
  current?: Prisma.ListingCurrentStatusUpdateManyWithoutStatusNestedInput
}

export type ListingStatusUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.ListingStatusHistoryUncheckedUpdateManyWithoutStatusNestedInput
  current?: Prisma.ListingCurrentStatusUncheckedUpdateManyWithoutStatusNestedInput
}

export type ListingStatusCreateManyInput = {
  id?: string
  name: string
  description?: string | null
}

export type ListingStatusUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ListingStatusUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ListingStatusCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ListingStatusMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ListingStatusMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ListingStatusScalarRelationFilter = {
  is?: Prisma.ListingStatusWhereInput
  isNot?: Prisma.ListingStatusWhereInput
}

export type ListingStatusCreateNestedOneWithoutHistoryInput = {
  create?: Prisma.XOR<Prisma.ListingStatusCreateWithoutHistoryInput, Prisma.ListingStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.ListingStatusCreateOrConnectWithoutHistoryInput
  connect?: Prisma.ListingStatusWhereUniqueInput
}

export type ListingStatusUpdateOneRequiredWithoutHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.ListingStatusCreateWithoutHistoryInput, Prisma.ListingStatusUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.ListingStatusCreateOrConnectWithoutHistoryInput
  upsert?: Prisma.ListingStatusUpsertWithoutHistoryInput
  connect?: Prisma.ListingStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListingStatusUpdateToOneWithWhereWithoutHistoryInput, Prisma.ListingStatusUpdateWithoutHistoryInput>, Prisma.ListingStatusUncheckedUpdateWithoutHistoryInput>
}

export type ListingStatusCreateNestedOneWithoutCurrentInput = {
  create?: Prisma.XOR<Prisma.ListingStatusCreateWithoutCurrentInput, Prisma.ListingStatusUncheckedCreateWithoutCurrentInput>
  connectOrCreate?: Prisma.ListingStatusCreateOrConnectWithoutCurrentInput
  connect?: Prisma.ListingStatusWhereUniqueInput
}

export type ListingStatusUpdateOneRequiredWithoutCurrentNestedInput = {
  create?: Prisma.XOR<Prisma.ListingStatusCreateWithoutCurrentInput, Prisma.ListingStatusUncheckedCreateWithoutCurrentInput>
  connectOrCreate?: Prisma.ListingStatusCreateOrConnectWithoutCurrentInput
  upsert?: Prisma.ListingStatusUpsertWithoutCurrentInput
  connect?: Prisma.ListingStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListingStatusUpdateToOneWithWhereWithoutCurrentInput, Prisma.ListingStatusUpdateWithoutCurrentInput>, Prisma.ListingStatusUncheckedUpdateWithoutCurrentInput>
}

export type ListingStatusCreateWithoutHistoryInput = {
  id?: string
  name: string
  description?: string | null
  current?: Prisma.ListingCurrentStatusCreateNestedManyWithoutStatusInput
}

export type ListingStatusUncheckedCreateWithoutHistoryInput = {
  id?: string
  name: string
  description?: string | null
  current?: Prisma.ListingCurrentStatusUncheckedCreateNestedManyWithoutStatusInput
}

export type ListingStatusCreateOrConnectWithoutHistoryInput = {
  where: Prisma.ListingStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingStatusCreateWithoutHistoryInput, Prisma.ListingStatusUncheckedCreateWithoutHistoryInput>
}

export type ListingStatusUpsertWithoutHistoryInput = {
  update: Prisma.XOR<Prisma.ListingStatusUpdateWithoutHistoryInput, Prisma.ListingStatusUncheckedUpdateWithoutHistoryInput>
  create: Prisma.XOR<Prisma.ListingStatusCreateWithoutHistoryInput, Prisma.ListingStatusUncheckedCreateWithoutHistoryInput>
  where?: Prisma.ListingStatusWhereInput
}

export type ListingStatusUpdateToOneWithWhereWithoutHistoryInput = {
  where?: Prisma.ListingStatusWhereInput
  data: Prisma.XOR<Prisma.ListingStatusUpdateWithoutHistoryInput, Prisma.ListingStatusUncheckedUpdateWithoutHistoryInput>
}

export type ListingStatusUpdateWithoutHistoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  current?: Prisma.ListingCurrentStatusUpdateManyWithoutStatusNestedInput
}

export type ListingStatusUncheckedUpdateWithoutHistoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  current?: Prisma.ListingCurrentStatusUncheckedUpdateManyWithoutStatusNestedInput
}

export type ListingStatusCreateWithoutCurrentInput = {
  id?: string
  name: string
  description?: string | null
  history?: Prisma.ListingStatusHistoryCreateNestedManyWithoutStatusInput
}

export type ListingStatusUncheckedCreateWithoutCurrentInput = {
  id?: string
  name: string
  description?: string | null
  history?: Prisma.ListingStatusHistoryUncheckedCreateNestedManyWithoutStatusInput
}

export type ListingStatusCreateOrConnectWithoutCurrentInput = {
  where: Prisma.ListingStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingStatusCreateWithoutCurrentInput, Prisma.ListingStatusUncheckedCreateWithoutCurrentInput>
}

export type ListingStatusUpsertWithoutCurrentInput = {
  update: Prisma.XOR<Prisma.ListingStatusUpdateWithoutCurrentInput, Prisma.ListingStatusUncheckedUpdateWithoutCurrentInput>
  create: Prisma.XOR<Prisma.ListingStatusCreateWithoutCurrentInput, Prisma.ListingStatusUncheckedCreateWithoutCurrentInput>
  where?: Prisma.ListingStatusWhereInput
}

export type ListingStatusUpdateToOneWithWhereWithoutCurrentInput = {
  where?: Prisma.ListingStatusWhereInput
  data: Prisma.XOR<Prisma.ListingStatusUpdateWithoutCurrentInput, Prisma.ListingStatusUncheckedUpdateWithoutCurrentInput>
}

export type ListingStatusUpdateWithoutCurrentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.ListingStatusHistoryUpdateManyWithoutStatusNestedInput
}

export type ListingStatusUncheckedUpdateWithoutCurrentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.ListingStatusHistoryUncheckedUpdateManyWithoutStatusNestedInput
}


/**
 * Count Type ListingStatusCountOutputType
 */

export type ListingStatusCountOutputType = {
  history: number
  current: number
}

export type ListingStatusCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  history?: boolean | ListingStatusCountOutputTypeCountHistoryArgs
  current?: boolean | ListingStatusCountOutputTypeCountCurrentArgs
}

/**
 * ListingStatusCountOutputType without action
 */
export type ListingStatusCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusCountOutputType
   */
  select?: Prisma.ListingStatusCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ListingStatusCountOutputType without action
 */
export type ListingStatusCountOutputTypeCountHistoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingStatusHistoryWhereInput
}

/**
 * ListingStatusCountOutputType without action
 */
export type ListingStatusCountOutputTypeCountCurrentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingCurrentStatusWhereInput
}


export type ListingStatusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  history?: boolean | Prisma.ListingStatus$historyArgs<ExtArgs>
  current?: boolean | Prisma.ListingStatus$currentArgs<ExtArgs>
  _count?: boolean | Prisma.ListingStatusCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingStatus"]>

export type ListingStatusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
}, ExtArgs["result"]["listingStatus"]>

export type ListingStatusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
}, ExtArgs["result"]["listingStatus"]>

export type ListingStatusSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
}

export type ListingStatusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description", ExtArgs["result"]["listingStatus"]>
export type ListingStatusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  history?: boolean | Prisma.ListingStatus$historyArgs<ExtArgs>
  current?: boolean | Prisma.ListingStatus$currentArgs<ExtArgs>
  _count?: boolean | Prisma.ListingStatusCountOutputTypeDefaultArgs<ExtArgs>
}
export type ListingStatusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ListingStatusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ListingStatusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ListingStatus"
  objects: {
    history: Prisma.$ListingStatusHistoryPayload<ExtArgs>[]
    current: Prisma.$ListingCurrentStatusPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
  }, ExtArgs["result"]["listingStatus"]>
  composites: {}
}

export type ListingStatusGetPayload<S extends boolean | null | undefined | ListingStatusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload, S>

export type ListingStatusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ListingStatusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ListingStatusCountAggregateInputType | true
  }

export interface ListingStatusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ListingStatus'], meta: { name: 'ListingStatus' } }
  /**
   * Find zero or one ListingStatus that matches the filter.
   * @param {ListingStatusFindUniqueArgs} args - Arguments to find a ListingStatus
   * @example
   * // Get one ListingStatus
   * const listingStatus = await prisma.listingStatus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ListingStatusFindUniqueArgs>(args: Prisma.SelectSubset<T, ListingStatusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ListingStatus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ListingStatusFindUniqueOrThrowArgs} args - Arguments to find a ListingStatus
   * @example
   * // Get one ListingStatus
   * const listingStatus = await prisma.listingStatus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ListingStatusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ListingStatusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingStatus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusFindFirstArgs} args - Arguments to find a ListingStatus
   * @example
   * // Get one ListingStatus
   * const listingStatus = await prisma.listingStatus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ListingStatusFindFirstArgs>(args?: Prisma.SelectSubset<T, ListingStatusFindFirstArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingStatus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusFindFirstOrThrowArgs} args - Arguments to find a ListingStatus
   * @example
   * // Get one ListingStatus
   * const listingStatus = await prisma.listingStatus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ListingStatusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ListingStatusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ListingStatuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ListingStatuses
   * const listingStatuses = await prisma.listingStatus.findMany()
   * 
   * // Get first 10 ListingStatuses
   * const listingStatuses = await prisma.listingStatus.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const listingStatusWithIdOnly = await prisma.listingStatus.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ListingStatusFindManyArgs>(args?: Prisma.SelectSubset<T, ListingStatusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ListingStatus.
   * @param {ListingStatusCreateArgs} args - Arguments to create a ListingStatus.
   * @example
   * // Create one ListingStatus
   * const ListingStatus = await prisma.listingStatus.create({
   *   data: {
   *     // ... data to create a ListingStatus
   *   }
   * })
   * 
   */
  create<T extends ListingStatusCreateArgs>(args: Prisma.SelectSubset<T, ListingStatusCreateArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ListingStatuses.
   * @param {ListingStatusCreateManyArgs} args - Arguments to create many ListingStatuses.
   * @example
   * // Create many ListingStatuses
   * const listingStatus = await prisma.listingStatus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ListingStatusCreateManyArgs>(args?: Prisma.SelectSubset<T, ListingStatusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ListingStatuses and returns the data saved in the database.
   * @param {ListingStatusCreateManyAndReturnArgs} args - Arguments to create many ListingStatuses.
   * @example
   * // Create many ListingStatuses
   * const listingStatus = await prisma.listingStatus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ListingStatuses and only return the `id`
   * const listingStatusWithIdOnly = await prisma.listingStatus.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ListingStatusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ListingStatusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ListingStatus.
   * @param {ListingStatusDeleteArgs} args - Arguments to delete one ListingStatus.
   * @example
   * // Delete one ListingStatus
   * const ListingStatus = await prisma.listingStatus.delete({
   *   where: {
   *     // ... filter to delete one ListingStatus
   *   }
   * })
   * 
   */
  delete<T extends ListingStatusDeleteArgs>(args: Prisma.SelectSubset<T, ListingStatusDeleteArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ListingStatus.
   * @param {ListingStatusUpdateArgs} args - Arguments to update one ListingStatus.
   * @example
   * // Update one ListingStatus
   * const listingStatus = await prisma.listingStatus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ListingStatusUpdateArgs>(args: Prisma.SelectSubset<T, ListingStatusUpdateArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ListingStatuses.
   * @param {ListingStatusDeleteManyArgs} args - Arguments to filter ListingStatuses to delete.
   * @example
   * // Delete a few ListingStatuses
   * const { count } = await prisma.listingStatus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ListingStatusDeleteManyArgs>(args?: Prisma.SelectSubset<T, ListingStatusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ListingStatuses
   * const listingStatus = await prisma.listingStatus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ListingStatusUpdateManyArgs>(args: Prisma.SelectSubset<T, ListingStatusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingStatuses and returns the data updated in the database.
   * @param {ListingStatusUpdateManyAndReturnArgs} args - Arguments to update many ListingStatuses.
   * @example
   * // Update many ListingStatuses
   * const listingStatus = await prisma.listingStatus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ListingStatuses and only return the `id`
   * const listingStatusWithIdOnly = await prisma.listingStatus.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ListingStatusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ListingStatusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ListingStatus.
   * @param {ListingStatusUpsertArgs} args - Arguments to update or create a ListingStatus.
   * @example
   * // Update or create a ListingStatus
   * const listingStatus = await prisma.listingStatus.upsert({
   *   create: {
   *     // ... data to create a ListingStatus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ListingStatus we want to update
   *   }
   * })
   */
  upsert<T extends ListingStatusUpsertArgs>(args: Prisma.SelectSubset<T, ListingStatusUpsertArgs<ExtArgs>>): Prisma.Prisma__ListingStatusClient<runtime.Types.Result.GetResult<Prisma.$ListingStatusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ListingStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusCountArgs} args - Arguments to filter ListingStatuses to count.
   * @example
   * // Count the number of ListingStatuses
   * const count = await prisma.listingStatus.count({
   *   where: {
   *     // ... the filter for the ListingStatuses we want to count
   *   }
   * })
  **/
  count<T extends ListingStatusCountArgs>(
    args?: Prisma.Subset<T, ListingStatusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ListingStatusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ListingStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ListingStatusAggregateArgs>(args: Prisma.Subset<T, ListingStatusAggregateArgs>): Prisma.PrismaPromise<GetListingStatusAggregateType<T>>

  /**
   * Group by ListingStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingStatusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ListingStatusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ListingStatusGroupByArgs['orderBy'] }
      : { orderBy?: ListingStatusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ListingStatusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetListingStatusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ListingStatus model
 */
readonly fields: ListingStatusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ListingStatus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ListingStatusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  history<T extends Prisma.ListingStatus$historyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListingStatus$historyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingStatusHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  current<T extends Prisma.ListingStatus$currentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListingStatus$currentArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingCurrentStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ListingStatus model
 */
export interface ListingStatusFieldRefs {
  readonly id: Prisma.FieldRef<"ListingStatus", 'String'>
  readonly name: Prisma.FieldRef<"ListingStatus", 'String'>
  readonly description: Prisma.FieldRef<"ListingStatus", 'String'>
}
    

// Custom InputTypes
/**
 * ListingStatus findUnique
 */
export type ListingStatusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatus to fetch.
   */
  where: Prisma.ListingStatusWhereUniqueInput
}

/**
 * ListingStatus findUniqueOrThrow
 */
export type ListingStatusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatus to fetch.
   */
  where: Prisma.ListingStatusWhereUniqueInput
}

/**
 * ListingStatus findFirst
 */
export type ListingStatusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatus to fetch.
   */
  where?: Prisma.ListingStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingStatuses to fetch.
   */
  orderBy?: Prisma.ListingStatusOrderByWithRelationInput | Prisma.ListingStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingStatuses.
   */
  cursor?: Prisma.ListingStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingStatuses.
   */
  distinct?: Prisma.ListingStatusScalarFieldEnum | Prisma.ListingStatusScalarFieldEnum[]
}

/**
 * ListingStatus findFirstOrThrow
 */
export type ListingStatusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatus to fetch.
   */
  where?: Prisma.ListingStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingStatuses to fetch.
   */
  orderBy?: Prisma.ListingStatusOrderByWithRelationInput | Prisma.ListingStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingStatuses.
   */
  cursor?: Prisma.ListingStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingStatuses.
   */
  distinct?: Prisma.ListingStatusScalarFieldEnum | Prisma.ListingStatusScalarFieldEnum[]
}

/**
 * ListingStatus findMany
 */
export type ListingStatusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
  /**
   * Filter, which ListingStatuses to fetch.
   */
  where?: Prisma.ListingStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingStatuses to fetch.
   */
  orderBy?: Prisma.ListingStatusOrderByWithRelationInput | Prisma.ListingStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ListingStatuses.
   */
  cursor?: Prisma.ListingStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingStatuses.
   */
  distinct?: Prisma.ListingStatusScalarFieldEnum | Prisma.ListingStatusScalarFieldEnum[]
}

/**
 * ListingStatus create
 */
export type ListingStatusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
  /**
   * The data needed to create a ListingStatus.
   */
  data: Prisma.XOR<Prisma.ListingStatusCreateInput, Prisma.ListingStatusUncheckedCreateInput>
}

/**
 * ListingStatus createMany
 */
export type ListingStatusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ListingStatuses.
   */
  data: Prisma.ListingStatusCreateManyInput | Prisma.ListingStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ListingStatus createManyAndReturn
 */
export type ListingStatusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * The data used to create many ListingStatuses.
   */
  data: Prisma.ListingStatusCreateManyInput | Prisma.ListingStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ListingStatus update
 */
export type ListingStatusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
  /**
   * The data needed to update a ListingStatus.
   */
  data: Prisma.XOR<Prisma.ListingStatusUpdateInput, Prisma.ListingStatusUncheckedUpdateInput>
  /**
   * Choose, which ListingStatus to update.
   */
  where: Prisma.ListingStatusWhereUniqueInput
}

/**
 * ListingStatus updateMany
 */
export type ListingStatusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ListingStatuses.
   */
  data: Prisma.XOR<Prisma.ListingStatusUpdateManyMutationInput, Prisma.ListingStatusUncheckedUpdateManyInput>
  /**
   * Filter which ListingStatuses to update
   */
  where?: Prisma.ListingStatusWhereInput
  /**
   * Limit how many ListingStatuses to update.
   */
  limit?: number
}

/**
 * ListingStatus updateManyAndReturn
 */
export type ListingStatusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * The data used to update ListingStatuses.
   */
  data: Prisma.XOR<Prisma.ListingStatusUpdateManyMutationInput, Prisma.ListingStatusUncheckedUpdateManyInput>
  /**
   * Filter which ListingStatuses to update
   */
  where?: Prisma.ListingStatusWhereInput
  /**
   * Limit how many ListingStatuses to update.
   */
  limit?: number
}

/**
 * ListingStatus upsert
 */
export type ListingStatusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
  /**
   * The filter to search for the ListingStatus to update in case it exists.
   */
  where: Prisma.ListingStatusWhereUniqueInput
  /**
   * In case the ListingStatus found by the `where` argument doesn't exist, create a new ListingStatus with this data.
   */
  create: Prisma.XOR<Prisma.ListingStatusCreateInput, Prisma.ListingStatusUncheckedCreateInput>
  /**
   * In case the ListingStatus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ListingStatusUpdateInput, Prisma.ListingStatusUncheckedUpdateInput>
}

/**
 * ListingStatus delete
 */
export type ListingStatusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
  /**
   * Filter which ListingStatus to delete.
   */
  where: Prisma.ListingStatusWhereUniqueInput
}

/**
 * ListingStatus deleteMany
 */
export type ListingStatusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingStatuses to delete
   */
  where?: Prisma.ListingStatusWhereInput
  /**
   * Limit how many ListingStatuses to delete.
   */
  limit?: number
}

/**
 * ListingStatus.history
 */
export type ListingStatus$historyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatusHistory
   */
  select?: Prisma.ListingStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatusHistory
   */
  omit?: Prisma.ListingStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusHistoryInclude<ExtArgs> | null
  where?: Prisma.ListingStatusHistoryWhereInput
  orderBy?: Prisma.ListingStatusHistoryOrderByWithRelationInput | Prisma.ListingStatusHistoryOrderByWithRelationInput[]
  cursor?: Prisma.ListingStatusHistoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ListingStatusHistoryScalarFieldEnum | Prisma.ListingStatusHistoryScalarFieldEnum[]
}

/**
 * ListingStatus.current
 */
export type ListingStatus$currentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCurrentStatus
   */
  select?: Prisma.ListingCurrentStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingCurrentStatus
   */
  omit?: Prisma.ListingCurrentStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingCurrentStatusInclude<ExtArgs> | null
  where?: Prisma.ListingCurrentStatusWhereInput
  orderBy?: Prisma.ListingCurrentStatusOrderByWithRelationInput | Prisma.ListingCurrentStatusOrderByWithRelationInput[]
  cursor?: Prisma.ListingCurrentStatusWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ListingCurrentStatusScalarFieldEnum | Prisma.ListingCurrentStatusScalarFieldEnum[]
}

/**
 * ListingStatus without action
 */
export type ListingStatusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingStatus
   */
  select?: Prisma.ListingStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingStatus
   */
  omit?: Prisma.ListingStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingStatusInclude<ExtArgs> | null
}
