
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Property` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Property
 * 
 */
export type PropertyModel = runtime.Types.Result.DefaultSelection<Prisma.$PropertyPayload>

export type AggregateProperty = {
  _count: PropertyCountAggregateOutputType | null
  _avg: PropertyAvgAggregateOutputType | null
  _sum: PropertySumAggregateOutputType | null
  _min: PropertyMinAggregateOutputType | null
  _max: PropertyMaxAggregateOutputType | null
}

export type PropertyAvgAggregateOutputType = {
  length: runtime.Decimal | null
  width: runtime.Decimal | null
  number_of_bathrooms: number | null
  number_of_rooms: number | null
}

export type PropertySumAggregateOutputType = {
  length: runtime.Decimal | null
  width: runtime.Decimal | null
  number_of_bathrooms: number | null
  number_of_rooms: number | null
}

export type PropertyMinAggregateOutputType = {
  id: string | null
  property_type: string | null
  length: runtime.Decimal | null
  width: runtime.Decimal | null
  number_of_bathrooms: number | null
  number_of_rooms: number | null
  is_active: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type PropertyMaxAggregateOutputType = {
  id: string | null
  property_type: string | null
  length: runtime.Decimal | null
  width: runtime.Decimal | null
  number_of_bathrooms: number | null
  number_of_rooms: number | null
  is_active: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type PropertyCountAggregateOutputType = {
  id: number
  property_type: number
  length: number
  width: number
  number_of_bathrooms: number
  number_of_rooms: number
  is_active: number
  created_at: number
  updated_at: number
  _all: number
}


export type PropertyAvgAggregateInputType = {
  length?: true
  width?: true
  number_of_bathrooms?: true
  number_of_rooms?: true
}

export type PropertySumAggregateInputType = {
  length?: true
  width?: true
  number_of_bathrooms?: true
  number_of_rooms?: true
}

export type PropertyMinAggregateInputType = {
  id?: true
  property_type?: true
  length?: true
  width?: true
  number_of_bathrooms?: true
  number_of_rooms?: true
  is_active?: true
  created_at?: true
  updated_at?: true
}

export type PropertyMaxAggregateInputType = {
  id?: true
  property_type?: true
  length?: true
  width?: true
  number_of_bathrooms?: true
  number_of_rooms?: true
  is_active?: true
  created_at?: true
  updated_at?: true
}

export type PropertyCountAggregateInputType = {
  id?: true
  property_type?: true
  length?: true
  width?: true
  number_of_bathrooms?: true
  number_of_rooms?: true
  is_active?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type PropertyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Property to aggregate.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Properties
  **/
  _count?: true | PropertyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PropertyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PropertySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PropertyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PropertyMaxAggregateInputType
}

export type GetPropertyAggregateType<T extends PropertyAggregateArgs> = {
      [P in keyof T & keyof AggregateProperty]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProperty[P]>
    : Prisma.GetScalarType<T[P], AggregateProperty[P]>
}




export type PropertyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PropertyWhereInput
  orderBy?: Prisma.PropertyOrderByWithAggregationInput | Prisma.PropertyOrderByWithAggregationInput[]
  by: Prisma.PropertyScalarFieldEnum[] | Prisma.PropertyScalarFieldEnum
  having?: Prisma.PropertyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PropertyCountAggregateInputType | true
  _avg?: PropertyAvgAggregateInputType
  _sum?: PropertySumAggregateInputType
  _min?: PropertyMinAggregateInputType
  _max?: PropertyMaxAggregateInputType
}

export type PropertyGroupByOutputType = {
  id: string
  property_type: string
  length: runtime.Decimal | null
  width: runtime.Decimal | null
  number_of_bathrooms: number
  number_of_rooms: number
  is_active: boolean
  created_at: Date
  updated_at: Date
  _count: PropertyCountAggregateOutputType | null
  _avg: PropertyAvgAggregateOutputType | null
  _sum: PropertySumAggregateOutputType | null
  _min: PropertyMinAggregateOutputType | null
  _max: PropertyMaxAggregateOutputType | null
}

export type GetPropertyGroupByPayload<T extends PropertyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PropertyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PropertyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PropertyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PropertyGroupByOutputType[P]>
      }
    >
  >



export type PropertyWhereInput = {
  AND?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  OR?: Prisma.PropertyWhereInput[]
  NOT?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  id?: Prisma.StringFilter<"Property"> | string
  property_type?: Prisma.StringFilter<"Property"> | string
  length?: Prisma.DecimalNullableFilter<"Property"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.DecimalNullableFilter<"Property"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFilter<"Property"> | number
  number_of_rooms?: Prisma.IntFilter<"Property"> | number
  is_active?: Prisma.BoolFilter<"Property"> | boolean
  created_at?: Prisma.DateTimeFilter<"Property"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Property"> | Date | string
  address?: Prisma.XOR<Prisma.AddressNullableScalarRelationFilter, Prisma.AddressWhereInput> | null
  additional_features?: Prisma.PropertyAdditionalFeatureListRelationFilter
}

export type PropertyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  property_type?: Prisma.SortOrder
  length?: Prisma.SortOrderInput | Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  number_of_bathrooms?: Prisma.SortOrder
  number_of_rooms?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  address?: Prisma.AddressOrderByWithRelationInput
  additional_features?: Prisma.PropertyAdditionalFeatureOrderByRelationAggregateInput
}

export type PropertyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  OR?: Prisma.PropertyWhereInput[]
  NOT?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  property_type?: Prisma.StringFilter<"Property"> | string
  length?: Prisma.DecimalNullableFilter<"Property"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.DecimalNullableFilter<"Property"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFilter<"Property"> | number
  number_of_rooms?: Prisma.IntFilter<"Property"> | number
  is_active?: Prisma.BoolFilter<"Property"> | boolean
  created_at?: Prisma.DateTimeFilter<"Property"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Property"> | Date | string
  address?: Prisma.XOR<Prisma.AddressNullableScalarRelationFilter, Prisma.AddressWhereInput> | null
  additional_features?: Prisma.PropertyAdditionalFeatureListRelationFilter
}, "id">

export type PropertyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  property_type?: Prisma.SortOrder
  length?: Prisma.SortOrderInput | Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  number_of_bathrooms?: Prisma.SortOrder
  number_of_rooms?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.PropertyCountOrderByAggregateInput
  _avg?: Prisma.PropertyAvgOrderByAggregateInput
  _max?: Prisma.PropertyMaxOrderByAggregateInput
  _min?: Prisma.PropertyMinOrderByAggregateInput
  _sum?: Prisma.PropertySumOrderByAggregateInput
}

export type PropertyScalarWhereWithAggregatesInput = {
  AND?: Prisma.PropertyScalarWhereWithAggregatesInput | Prisma.PropertyScalarWhereWithAggregatesInput[]
  OR?: Prisma.PropertyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PropertyScalarWhereWithAggregatesInput | Prisma.PropertyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Property"> | string
  property_type?: Prisma.StringWithAggregatesFilter<"Property"> | string
  length?: Prisma.DecimalNullableWithAggregatesFilter<"Property"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.DecimalNullableWithAggregatesFilter<"Property"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntWithAggregatesFilter<"Property"> | number
  number_of_rooms?: Prisma.IntWithAggregatesFilter<"Property"> | number
  is_active?: Prisma.BoolWithAggregatesFilter<"Property"> | boolean
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Property"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Property"> | Date | string
}

export type PropertyCreateInput = {
  id?: string
  property_type: string
  length?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms: number
  number_of_rooms: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  address?: Prisma.AddressCreateNestedOneWithoutPropertyInput
  additional_features?: Prisma.PropertyAdditionalFeatureCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateInput = {
  id?: string
  property_type: string
  length?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms: number
  number_of_rooms: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  address?: Prisma.AddressUncheckedCreateNestedOneWithoutPropertyInput
  additional_features?: Prisma.PropertyAdditionalFeatureUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_type?: Prisma.StringFieldUpdateOperationsInput | string
  length?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  number_of_rooms?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  address?: Prisma.AddressUpdateOneWithoutPropertyNestedInput
  additional_features?: Prisma.PropertyAdditionalFeatureUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_type?: Prisma.StringFieldUpdateOperationsInput | string
  length?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  number_of_rooms?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  address?: Prisma.AddressUncheckedUpdateOneWithoutPropertyNestedInput
  additional_features?: Prisma.PropertyAdditionalFeatureUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateManyInput = {
  id?: string
  property_type: string
  length?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms: number
  number_of_rooms: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type PropertyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_type?: Prisma.StringFieldUpdateOperationsInput | string
  length?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  number_of_rooms?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PropertyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_type?: Prisma.StringFieldUpdateOperationsInput | string
  length?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  number_of_rooms?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PropertyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_type?: Prisma.SortOrder
  length?: Prisma.SortOrder
  width?: Prisma.SortOrder
  number_of_bathrooms?: Prisma.SortOrder
  number_of_rooms?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PropertyAvgOrderByAggregateInput = {
  length?: Prisma.SortOrder
  width?: Prisma.SortOrder
  number_of_bathrooms?: Prisma.SortOrder
  number_of_rooms?: Prisma.SortOrder
}

export type PropertyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_type?: Prisma.SortOrder
  length?: Prisma.SortOrder
  width?: Prisma.SortOrder
  number_of_bathrooms?: Prisma.SortOrder
  number_of_rooms?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PropertyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_type?: Prisma.SortOrder
  length?: Prisma.SortOrder
  width?: Prisma.SortOrder
  number_of_bathrooms?: Prisma.SortOrder
  number_of_rooms?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PropertySumOrderByAggregateInput = {
  length?: Prisma.SortOrder
  width?: Prisma.SortOrder
  number_of_bathrooms?: Prisma.SortOrder
  number_of_rooms?: Prisma.SortOrder
}

export type PropertyScalarRelationFilter = {
  is?: Prisma.PropertyWhereInput
  isNot?: Prisma.PropertyWhereInput
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PropertyCreateNestedOneWithoutAddressInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutAddressInput, Prisma.PropertyUncheckedCreateWithoutAddressInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutAddressInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutAddressNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutAddressInput, Prisma.PropertyUncheckedCreateWithoutAddressInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutAddressInput
  upsert?: Prisma.PropertyUpsertWithoutAddressInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutAddressInput, Prisma.PropertyUpdateWithoutAddressInput>, Prisma.PropertyUncheckedUpdateWithoutAddressInput>
}

export type PropertyCreateNestedOneWithoutAdditional_featuresInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutAdditional_featuresInput, Prisma.PropertyUncheckedCreateWithoutAdditional_featuresInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutAdditional_featuresInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutAdditional_featuresNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutAdditional_featuresInput, Prisma.PropertyUncheckedCreateWithoutAdditional_featuresInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutAdditional_featuresInput
  upsert?: Prisma.PropertyUpsertWithoutAdditional_featuresInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutAdditional_featuresInput, Prisma.PropertyUpdateWithoutAdditional_featuresInput>, Prisma.PropertyUncheckedUpdateWithoutAdditional_featuresInput>
}

export type PropertyCreateWithoutAddressInput = {
  id?: string
  property_type: string
  length?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms: number
  number_of_rooms: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  additional_features?: Prisma.PropertyAdditionalFeatureCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutAddressInput = {
  id?: string
  property_type: string
  length?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms: number
  number_of_rooms: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  additional_features?: Prisma.PropertyAdditionalFeatureUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutAddressInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutAddressInput, Prisma.PropertyUncheckedCreateWithoutAddressInput>
}

export type PropertyUpsertWithoutAddressInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutAddressInput, Prisma.PropertyUncheckedUpdateWithoutAddressInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutAddressInput, Prisma.PropertyUncheckedCreateWithoutAddressInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutAddressInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutAddressInput, Prisma.PropertyUncheckedUpdateWithoutAddressInput>
}

export type PropertyUpdateWithoutAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_type?: Prisma.StringFieldUpdateOperationsInput | string
  length?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  number_of_rooms?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  additional_features?: Prisma.PropertyAdditionalFeatureUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_type?: Prisma.StringFieldUpdateOperationsInput | string
  length?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  number_of_rooms?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  additional_features?: Prisma.PropertyAdditionalFeatureUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateWithoutAdditional_featuresInput = {
  id?: string
  property_type: string
  length?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms: number
  number_of_rooms: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  address?: Prisma.AddressCreateNestedOneWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutAdditional_featuresInput = {
  id?: string
  property_type: string
  length?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms: number
  number_of_rooms: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  address?: Prisma.AddressUncheckedCreateNestedOneWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutAdditional_featuresInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutAdditional_featuresInput, Prisma.PropertyUncheckedCreateWithoutAdditional_featuresInput>
}

export type PropertyUpsertWithoutAdditional_featuresInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutAdditional_featuresInput, Prisma.PropertyUncheckedUpdateWithoutAdditional_featuresInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutAdditional_featuresInput, Prisma.PropertyUncheckedCreateWithoutAdditional_featuresInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutAdditional_featuresInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutAdditional_featuresInput, Prisma.PropertyUncheckedUpdateWithoutAdditional_featuresInput>
}

export type PropertyUpdateWithoutAdditional_featuresInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_type?: Prisma.StringFieldUpdateOperationsInput | string
  length?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  number_of_rooms?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  address?: Prisma.AddressUpdateOneWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutAdditional_featuresInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_type?: Prisma.StringFieldUpdateOperationsInput | string
  length?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  width?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  number_of_bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  number_of_rooms?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  address?: Prisma.AddressUncheckedUpdateOneWithoutPropertyNestedInput
}


/**
 * Count Type PropertyCountOutputType
 */

export type PropertyCountOutputType = {
  additional_features: number
}

export type PropertyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  additional_features?: boolean | PropertyCountOutputTypeCountAdditional_featuresArgs
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PropertyCountOutputType
   */
  select?: Prisma.PropertyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountAdditional_featuresArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PropertyAdditionalFeatureWhereInput
}


export type PropertySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_type?: boolean
  length?: boolean
  width?: boolean
  number_of_bathrooms?: boolean
  number_of_rooms?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
  address?: boolean | Prisma.Property$addressArgs<ExtArgs>
  additional_features?: boolean | Prisma.Property$additional_featuresArgs<ExtArgs>
  _count?: boolean | Prisma.PropertyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["property"]>

export type PropertySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_type?: boolean
  length?: boolean
  width?: boolean
  number_of_bathrooms?: boolean
  number_of_rooms?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["property"]>

export type PropertySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_type?: boolean
  length?: boolean
  width?: boolean
  number_of_bathrooms?: boolean
  number_of_rooms?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["property"]>

export type PropertySelectScalar = {
  id?: boolean
  property_type?: boolean
  length?: boolean
  width?: boolean
  number_of_bathrooms?: boolean
  number_of_rooms?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type PropertyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "property_type" | "length" | "width" | "number_of_bathrooms" | "number_of_rooms" | "is_active" | "created_at" | "updated_at", ExtArgs["result"]["property"]>
export type PropertyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  address?: boolean | Prisma.Property$addressArgs<ExtArgs>
  additional_features?: boolean | Prisma.Property$additional_featuresArgs<ExtArgs>
  _count?: boolean | Prisma.PropertyCountOutputTypeDefaultArgs<ExtArgs>
}
export type PropertyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PropertyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PropertyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Property"
  objects: {
    address: Prisma.$AddressPayload<ExtArgs> | null
    additional_features: Prisma.$PropertyAdditionalFeaturePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    property_type: string
    length: runtime.Decimal | null
    width: runtime.Decimal | null
    number_of_bathrooms: number
    number_of_rooms: number
    is_active: boolean
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["property"]>
  composites: {}
}

export type PropertyGetPayload<S extends boolean | null | undefined | PropertyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PropertyPayload, S>

export type PropertyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PropertyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PropertyCountAggregateInputType | true
  }

export interface PropertyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Property'], meta: { name: 'Property' } }
  /**
   * Find zero or one Property that matches the filter.
   * @param {PropertyFindUniqueArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PropertyFindUniqueArgs>(args: Prisma.SelectSubset<T, PropertyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Property that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PropertyFindUniqueOrThrowArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PropertyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PropertyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindFirstArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PropertyFindFirstArgs>(args?: Prisma.SelectSubset<T, PropertyFindFirstArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindFirstOrThrowArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PropertyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PropertyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Properties that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Properties
   * const properties = await prisma.property.findMany()
   * 
   * // Get first 10 Properties
   * const properties = await prisma.property.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const propertyWithIdOnly = await prisma.property.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PropertyFindManyArgs>(args?: Prisma.SelectSubset<T, PropertyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Property.
   * @param {PropertyCreateArgs} args - Arguments to create a Property.
   * @example
   * // Create one Property
   * const Property = await prisma.property.create({
   *   data: {
   *     // ... data to create a Property
   *   }
   * })
   * 
   */
  create<T extends PropertyCreateArgs>(args: Prisma.SelectSubset<T, PropertyCreateArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Properties.
   * @param {PropertyCreateManyArgs} args - Arguments to create many Properties.
   * @example
   * // Create many Properties
   * const property = await prisma.property.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PropertyCreateManyArgs>(args?: Prisma.SelectSubset<T, PropertyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Properties and returns the data saved in the database.
   * @param {PropertyCreateManyAndReturnArgs} args - Arguments to create many Properties.
   * @example
   * // Create many Properties
   * const property = await prisma.property.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Properties and only return the `id`
   * const propertyWithIdOnly = await prisma.property.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PropertyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PropertyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Property.
   * @param {PropertyDeleteArgs} args - Arguments to delete one Property.
   * @example
   * // Delete one Property
   * const Property = await prisma.property.delete({
   *   where: {
   *     // ... filter to delete one Property
   *   }
   * })
   * 
   */
  delete<T extends PropertyDeleteArgs>(args: Prisma.SelectSubset<T, PropertyDeleteArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Property.
   * @param {PropertyUpdateArgs} args - Arguments to update one Property.
   * @example
   * // Update one Property
   * const property = await prisma.property.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PropertyUpdateArgs>(args: Prisma.SelectSubset<T, PropertyUpdateArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Properties.
   * @param {PropertyDeleteManyArgs} args - Arguments to filter Properties to delete.
   * @example
   * // Delete a few Properties
   * const { count } = await prisma.property.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PropertyDeleteManyArgs>(args?: Prisma.SelectSubset<T, PropertyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Properties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Properties
   * const property = await prisma.property.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PropertyUpdateManyArgs>(args: Prisma.SelectSubset<T, PropertyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Properties and returns the data updated in the database.
   * @param {PropertyUpdateManyAndReturnArgs} args - Arguments to update many Properties.
   * @example
   * // Update many Properties
   * const property = await prisma.property.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Properties and only return the `id`
   * const propertyWithIdOnly = await prisma.property.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PropertyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PropertyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Property.
   * @param {PropertyUpsertArgs} args - Arguments to update or create a Property.
   * @example
   * // Update or create a Property
   * const property = await prisma.property.upsert({
   *   create: {
   *     // ... data to create a Property
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Property we want to update
   *   }
   * })
   */
  upsert<T extends PropertyUpsertArgs>(args: Prisma.SelectSubset<T, PropertyUpsertArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Properties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyCountArgs} args - Arguments to filter Properties to count.
   * @example
   * // Count the number of Properties
   * const count = await prisma.property.count({
   *   where: {
   *     // ... the filter for the Properties we want to count
   *   }
   * })
  **/
  count<T extends PropertyCountArgs>(
    args?: Prisma.Subset<T, PropertyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PropertyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Property.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PropertyAggregateArgs>(args: Prisma.Subset<T, PropertyAggregateArgs>): Prisma.PrismaPromise<GetPropertyAggregateType<T>>

  /**
   * Group by Property.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PropertyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PropertyGroupByArgs['orderBy'] }
      : { orderBy?: PropertyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PropertyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPropertyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Property model
 */
readonly fields: PropertyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Property.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PropertyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  address<T extends Prisma.Property$addressArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$addressArgs<ExtArgs>>): Prisma.Prisma__AddressClient<runtime.Types.Result.GetResult<Prisma.$AddressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  additional_features<T extends Prisma.Property$additional_featuresArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$additional_featuresArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyAdditionalFeaturePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Property model
 */
export interface PropertyFieldRefs {
  readonly id: Prisma.FieldRef<"Property", 'String'>
  readonly property_type: Prisma.FieldRef<"Property", 'String'>
  readonly length: Prisma.FieldRef<"Property", 'Decimal'>
  readonly width: Prisma.FieldRef<"Property", 'Decimal'>
  readonly number_of_bathrooms: Prisma.FieldRef<"Property", 'Int'>
  readonly number_of_rooms: Prisma.FieldRef<"Property", 'Int'>
  readonly is_active: Prisma.FieldRef<"Property", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"Property", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Property", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Property findUnique
 */
export type PropertyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property findUniqueOrThrow
 */
export type PropertyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property findFirst
 */
export type PropertyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Properties.
   */
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property findFirstOrThrow
 */
export type PropertyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Properties.
   */
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property findMany
 */
export type PropertyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Properties to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Properties.
   */
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property create
 */
export type PropertyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The data needed to create a Property.
   */
  data: Prisma.XOR<Prisma.PropertyCreateInput, Prisma.PropertyUncheckedCreateInput>
}

/**
 * Property createMany
 */
export type PropertyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Properties.
   */
  data: Prisma.PropertyCreateManyInput | Prisma.PropertyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Property createManyAndReturn
 */
export type PropertyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * The data used to create many Properties.
   */
  data: Prisma.PropertyCreateManyInput | Prisma.PropertyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Property update
 */
export type PropertyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The data needed to update a Property.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateInput, Prisma.PropertyUncheckedUpdateInput>
  /**
   * Choose, which Property to update.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property updateMany
 */
export type PropertyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Properties.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyInput>
  /**
   * Filter which Properties to update
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to update.
   */
  limit?: number
}

/**
 * Property updateManyAndReturn
 */
export type PropertyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * The data used to update Properties.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyInput>
  /**
   * Filter which Properties to update
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to update.
   */
  limit?: number
}

/**
 * Property upsert
 */
export type PropertyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The filter to search for the Property to update in case it exists.
   */
  where: Prisma.PropertyWhereUniqueInput
  /**
   * In case the Property found by the `where` argument doesn't exist, create a new Property with this data.
   */
  create: Prisma.XOR<Prisma.PropertyCreateInput, Prisma.PropertyUncheckedCreateInput>
  /**
   * In case the Property was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PropertyUpdateInput, Prisma.PropertyUncheckedUpdateInput>
}

/**
 * Property delete
 */
export type PropertyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter which Property to delete.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property deleteMany
 */
export type PropertyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Properties to delete
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to delete.
   */
  limit?: number
}

/**
 * Property.address
 */
export type Property$addressArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Address
   */
  select?: Prisma.AddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Address
   */
  omit?: Prisma.AddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AddressInclude<ExtArgs> | null
  where?: Prisma.AddressWhereInput
}

/**
 * Property.additional_features
 */
export type Property$additional_featuresArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PropertyAdditionalFeature
   */
  select?: Prisma.PropertyAdditionalFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PropertyAdditionalFeature
   */
  omit?: Prisma.PropertyAdditionalFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyAdditionalFeatureInclude<ExtArgs> | null
  where?: Prisma.PropertyAdditionalFeatureWhereInput
  orderBy?: Prisma.PropertyAdditionalFeatureOrderByWithRelationInput | Prisma.PropertyAdditionalFeatureOrderByWithRelationInput[]
  cursor?: Prisma.PropertyAdditionalFeatureWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PropertyAdditionalFeatureScalarFieldEnum | Prisma.PropertyAdditionalFeatureScalarFieldEnum[]
}

/**
 * Property without action
 */
export type PropertyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
}
