
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  user_type: string | null
  document_type_id: string | null
  document_number: string | null
  mail: string | null
  hashed_password: string | null
  phone_number: string | null
  is_active: boolean | null
  registration_date: Date | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  user_type: string | null
  document_type_id: string | null
  document_number: string | null
  mail: string | null
  hashed_password: string | null
  phone_number: string | null
  is_active: boolean | null
  registration_date: Date | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type UserCountAggregateOutputType = {
  id: number
  user_type: number
  document_type_id: number
  document_number: number
  mail: number
  hashed_password: number
  phone_number: number
  is_active: number
  registration_date: number
  created_at: number
  updated_at: number
  deleted_at: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  user_type?: true
  document_type_id?: true
  document_number?: true
  mail?: true
  hashed_password?: true
  phone_number?: true
  is_active?: true
  registration_date?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  user_type?: true
  document_type_id?: true
  document_number?: true
  mail?: true
  hashed_password?: true
  phone_number?: true
  is_active?: true
  registration_date?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type UserCountAggregateInputType = {
  id?: true
  user_type?: true
  document_type_id?: true
  document_number?: true
  mail?: true
  hashed_password?: true
  phone_number?: true
  is_active?: true
  registration_date?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  user_type: string
  document_type_id: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active: boolean
  registration_date: Date
  created_at: Date
  updated_at: Date
  deleted_at: Date | null
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  user_type?: Prisma.StringFilter<"User"> | string
  document_type_id?: Prisma.StringFilter<"User"> | string
  document_number?: Prisma.StringFilter<"User"> | string
  mail?: Prisma.StringFilter<"User"> | string
  hashed_password?: Prisma.StringFilter<"User"> | string
  phone_number?: Prisma.StringFilter<"User"> | string
  is_active?: Prisma.BoolFilter<"User"> | boolean
  registration_date?: Prisma.DateTimeFilter<"User"> | Date | string
  created_at?: Prisma.DateTimeFilter<"User"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"User"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  document_type?: Prisma.XOR<Prisma.DocumentTypeScalarRelationFilter, Prisma.DocumentTypeWhereInput>
  natural_person?: Prisma.XOR<Prisma.NaturalPersonDetailNullableScalarRelationFilter, Prisma.NaturalPersonDetailWhereInput> | null
  legal_person?: Prisma.XOR<Prisma.LegalPersonDetailNullableScalarRelationFilter, Prisma.LegalPersonDetailWhereInput> | null
  users_roles?: Prisma.UserRoleListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  document_type_id?: Prisma.SortOrder
  document_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  hashed_password?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  registration_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  document_type?: Prisma.DocumentTypeOrderByWithRelationInput
  natural_person?: Prisma.NaturalPersonDetailOrderByWithRelationInput
  legal_person?: Prisma.LegalPersonDetailOrderByWithRelationInput
  users_roles?: Prisma.UserRoleOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  mail?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  user_type?: Prisma.StringFilter<"User"> | string
  document_type_id?: Prisma.StringFilter<"User"> | string
  document_number?: Prisma.StringFilter<"User"> | string
  hashed_password?: Prisma.StringFilter<"User"> | string
  phone_number?: Prisma.StringFilter<"User"> | string
  is_active?: Prisma.BoolFilter<"User"> | boolean
  registration_date?: Prisma.DateTimeFilter<"User"> | Date | string
  created_at?: Prisma.DateTimeFilter<"User"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"User"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  document_type?: Prisma.XOR<Prisma.DocumentTypeScalarRelationFilter, Prisma.DocumentTypeWhereInput>
  natural_person?: Prisma.XOR<Prisma.NaturalPersonDetailNullableScalarRelationFilter, Prisma.NaturalPersonDetailWhereInput> | null
  legal_person?: Prisma.XOR<Prisma.LegalPersonDetailNullableScalarRelationFilter, Prisma.LegalPersonDetailWhereInput> | null
  users_roles?: Prisma.UserRoleListRelationFilter
}, "id" | "mail">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  document_type_id?: Prisma.SortOrder
  document_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  hashed_password?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  registration_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  user_type?: Prisma.StringWithAggregatesFilter<"User"> | string
  document_type_id?: Prisma.StringWithAggregatesFilter<"User"> | string
  document_number?: Prisma.StringWithAggregatesFilter<"User"> | string
  mail?: Prisma.StringWithAggregatesFilter<"User"> | string
  hashed_password?: Prisma.StringWithAggregatesFilter<"User"> | string
  phone_number?: Prisma.StringWithAggregatesFilter<"User"> | string
  is_active?: Prisma.BoolWithAggregatesFilter<"User"> | boolean
  registration_date?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"User"> | Date | string | null
}

export type UserCreateInput = {
  id?: string
  user_type: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  document_type: Prisma.DocumentTypeCreateNestedOneWithoutUsersInput
  natural_person?: Prisma.NaturalPersonDetailCreateNestedOneWithoutUserInput
  legal_person?: Prisma.LegalPersonDetailCreateNestedOneWithoutUserInput
  users_roles?: Prisma.UserRoleCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: string
  user_type: string
  document_type_id: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  natural_person?: Prisma.NaturalPersonDetailUncheckedCreateNestedOneWithoutUserInput
  legal_person?: Prisma.LegalPersonDetailUncheckedCreateNestedOneWithoutUserInput
  users_roles?: Prisma.UserRoleUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  document_type?: Prisma.DocumentTypeUpdateOneRequiredWithoutUsersNestedInput
  natural_person?: Prisma.NaturalPersonDetailUpdateOneWithoutUserNestedInput
  legal_person?: Prisma.LegalPersonDetailUpdateOneWithoutUserNestedInput
  users_roles?: Prisma.UserRoleUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_type_id?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  natural_person?: Prisma.NaturalPersonDetailUncheckedUpdateOneWithoutUserNestedInput
  legal_person?: Prisma.LegalPersonDetailUncheckedUpdateOneWithoutUserNestedInput
  users_roles?: Prisma.UserRoleUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: string
  user_type: string
  document_type_id: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_type_id?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  document_type_id?: Prisma.SortOrder
  document_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  hashed_password?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  registration_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  document_type_id?: Prisma.SortOrder
  document_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  hashed_password?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  registration_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  document_type_id?: Prisma.SortOrder
  document_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  hashed_password?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  registration_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type UserListRelationFilter = {
  every?: Prisma.UserWhereInput
  some?: Prisma.UserWhereInput
  none?: Prisma.UserWhereInput
}

export type UserOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type UserCreateNestedManyWithoutDocument_typeInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutDocument_typeInput, Prisma.UserUncheckedCreateWithoutDocument_typeInput> | Prisma.UserCreateWithoutDocument_typeInput[] | Prisma.UserUncheckedCreateWithoutDocument_typeInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutDocument_typeInput | Prisma.UserCreateOrConnectWithoutDocument_typeInput[]
  createMany?: Prisma.UserCreateManyDocument_typeInputEnvelope
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
}

export type UserUncheckedCreateNestedManyWithoutDocument_typeInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutDocument_typeInput, Prisma.UserUncheckedCreateWithoutDocument_typeInput> | Prisma.UserCreateWithoutDocument_typeInput[] | Prisma.UserUncheckedCreateWithoutDocument_typeInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutDocument_typeInput | Prisma.UserCreateOrConnectWithoutDocument_typeInput[]
  createMany?: Prisma.UserCreateManyDocument_typeInputEnvelope
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
}

export type UserUpdateManyWithoutDocument_typeNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutDocument_typeInput, Prisma.UserUncheckedCreateWithoutDocument_typeInput> | Prisma.UserCreateWithoutDocument_typeInput[] | Prisma.UserUncheckedCreateWithoutDocument_typeInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutDocument_typeInput | Prisma.UserCreateOrConnectWithoutDocument_typeInput[]
  upsert?: Prisma.UserUpsertWithWhereUniqueWithoutDocument_typeInput | Prisma.UserUpsertWithWhereUniqueWithoutDocument_typeInput[]
  createMany?: Prisma.UserCreateManyDocument_typeInputEnvelope
  set?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  disconnect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  delete?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  update?: Prisma.UserUpdateWithWhereUniqueWithoutDocument_typeInput | Prisma.UserUpdateWithWhereUniqueWithoutDocument_typeInput[]
  updateMany?: Prisma.UserUpdateManyWithWhereWithoutDocument_typeInput | Prisma.UserUpdateManyWithWhereWithoutDocument_typeInput[]
  deleteMany?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
}

export type UserUncheckedUpdateManyWithoutDocument_typeNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutDocument_typeInput, Prisma.UserUncheckedCreateWithoutDocument_typeInput> | Prisma.UserCreateWithoutDocument_typeInput[] | Prisma.UserUncheckedCreateWithoutDocument_typeInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutDocument_typeInput | Prisma.UserCreateOrConnectWithoutDocument_typeInput[]
  upsert?: Prisma.UserUpsertWithWhereUniqueWithoutDocument_typeInput | Prisma.UserUpsertWithWhereUniqueWithoutDocument_typeInput[]
  createMany?: Prisma.UserCreateManyDocument_typeInputEnvelope
  set?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  disconnect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  delete?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  update?: Prisma.UserUpdateWithWhereUniqueWithoutDocument_typeInput | Prisma.UserUpdateWithWhereUniqueWithoutDocument_typeInput[]
  updateMany?: Prisma.UserUpdateManyWithWhereWithoutDocument_typeInput | Prisma.UserUpdateManyWithWhereWithoutDocument_typeInput[]
  deleteMany?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
}

export type UserCreateNestedOneWithoutNatural_personInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutNatural_personInput, Prisma.UserUncheckedCreateWithoutNatural_personInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutNatural_personInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutNatural_personNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutNatural_personInput, Prisma.UserUncheckedCreateWithoutNatural_personInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutNatural_personInput
  upsert?: Prisma.UserUpsertWithoutNatural_personInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutNatural_personInput, Prisma.UserUpdateWithoutNatural_personInput>, Prisma.UserUncheckedUpdateWithoutNatural_personInput>
}

export type UserCreateNestedOneWithoutLegal_personInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutLegal_personInput, Prisma.UserUncheckedCreateWithoutLegal_personInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutLegal_personInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutLegal_personNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutLegal_personInput, Prisma.UserUncheckedCreateWithoutLegal_personInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutLegal_personInput
  upsert?: Prisma.UserUpsertWithoutLegal_personInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutLegal_personInput, Prisma.UserUpdateWithoutLegal_personInput>, Prisma.UserUncheckedUpdateWithoutLegal_personInput>
}

export type UserCreateNestedOneWithoutUsers_rolesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUsers_rolesInput, Prisma.UserUncheckedCreateWithoutUsers_rolesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUsers_rolesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutUsers_rolesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUsers_rolesInput, Prisma.UserUncheckedCreateWithoutUsers_rolesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUsers_rolesInput
  upsert?: Prisma.UserUpsertWithoutUsers_rolesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutUsers_rolesInput, Prisma.UserUpdateWithoutUsers_rolesInput>, Prisma.UserUncheckedUpdateWithoutUsers_rolesInput>
}

export type UserCreateWithoutDocument_typeInput = {
  id?: string
  user_type: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  natural_person?: Prisma.NaturalPersonDetailCreateNestedOneWithoutUserInput
  legal_person?: Prisma.LegalPersonDetailCreateNestedOneWithoutUserInput
  users_roles?: Prisma.UserRoleCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutDocument_typeInput = {
  id?: string
  user_type: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  natural_person?: Prisma.NaturalPersonDetailUncheckedCreateNestedOneWithoutUserInput
  legal_person?: Prisma.LegalPersonDetailUncheckedCreateNestedOneWithoutUserInput
  users_roles?: Prisma.UserRoleUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutDocument_typeInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutDocument_typeInput, Prisma.UserUncheckedCreateWithoutDocument_typeInput>
}

export type UserCreateManyDocument_typeInputEnvelope = {
  data: Prisma.UserCreateManyDocument_typeInput | Prisma.UserCreateManyDocument_typeInput[]
  skipDuplicates?: boolean
}

export type UserUpsertWithWhereUniqueWithoutDocument_typeInput = {
  where: Prisma.UserWhereUniqueInput
  update: Prisma.XOR<Prisma.UserUpdateWithoutDocument_typeInput, Prisma.UserUncheckedUpdateWithoutDocument_typeInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutDocument_typeInput, Prisma.UserUncheckedCreateWithoutDocument_typeInput>
}

export type UserUpdateWithWhereUniqueWithoutDocument_typeInput = {
  where: Prisma.UserWhereUniqueInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutDocument_typeInput, Prisma.UserUncheckedUpdateWithoutDocument_typeInput>
}

export type UserUpdateManyWithWhereWithoutDocument_typeInput = {
  where: Prisma.UserScalarWhereInput
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyWithoutDocument_typeInput>
}

export type UserScalarWhereInput = {
  AND?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
  OR?: Prisma.UserScalarWhereInput[]
  NOT?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  user_type?: Prisma.StringFilter<"User"> | string
  document_type_id?: Prisma.StringFilter<"User"> | string
  document_number?: Prisma.StringFilter<"User"> | string
  mail?: Prisma.StringFilter<"User"> | string
  hashed_password?: Prisma.StringFilter<"User"> | string
  phone_number?: Prisma.StringFilter<"User"> | string
  is_active?: Prisma.BoolFilter<"User"> | boolean
  registration_date?: Prisma.DateTimeFilter<"User"> | Date | string
  created_at?: Prisma.DateTimeFilter<"User"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"User"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
}

export type UserCreateWithoutNatural_personInput = {
  id?: string
  user_type: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  document_type: Prisma.DocumentTypeCreateNestedOneWithoutUsersInput
  legal_person?: Prisma.LegalPersonDetailCreateNestedOneWithoutUserInput
  users_roles?: Prisma.UserRoleCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutNatural_personInput = {
  id?: string
  user_type: string
  document_type_id: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  legal_person?: Prisma.LegalPersonDetailUncheckedCreateNestedOneWithoutUserInput
  users_roles?: Prisma.UserRoleUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutNatural_personInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutNatural_personInput, Prisma.UserUncheckedCreateWithoutNatural_personInput>
}

export type UserUpsertWithoutNatural_personInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutNatural_personInput, Prisma.UserUncheckedUpdateWithoutNatural_personInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutNatural_personInput, Prisma.UserUncheckedCreateWithoutNatural_personInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutNatural_personInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutNatural_personInput, Prisma.UserUncheckedUpdateWithoutNatural_personInput>
}

export type UserUpdateWithoutNatural_personInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  document_type?: Prisma.DocumentTypeUpdateOneRequiredWithoutUsersNestedInput
  legal_person?: Prisma.LegalPersonDetailUpdateOneWithoutUserNestedInput
  users_roles?: Prisma.UserRoleUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutNatural_personInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_type_id?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  legal_person?: Prisma.LegalPersonDetailUncheckedUpdateOneWithoutUserNestedInput
  users_roles?: Prisma.UserRoleUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutLegal_personInput = {
  id?: string
  user_type: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  document_type: Prisma.DocumentTypeCreateNestedOneWithoutUsersInput
  natural_person?: Prisma.NaturalPersonDetailCreateNestedOneWithoutUserInput
  users_roles?: Prisma.UserRoleCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutLegal_personInput = {
  id?: string
  user_type: string
  document_type_id: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  natural_person?: Prisma.NaturalPersonDetailUncheckedCreateNestedOneWithoutUserInput
  users_roles?: Prisma.UserRoleUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutLegal_personInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutLegal_personInput, Prisma.UserUncheckedCreateWithoutLegal_personInput>
}

export type UserUpsertWithoutLegal_personInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutLegal_personInput, Prisma.UserUncheckedUpdateWithoutLegal_personInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutLegal_personInput, Prisma.UserUncheckedCreateWithoutLegal_personInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutLegal_personInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutLegal_personInput, Prisma.UserUncheckedUpdateWithoutLegal_personInput>
}

export type UserUpdateWithoutLegal_personInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  document_type?: Prisma.DocumentTypeUpdateOneRequiredWithoutUsersNestedInput
  natural_person?: Prisma.NaturalPersonDetailUpdateOneWithoutUserNestedInput
  users_roles?: Prisma.UserRoleUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutLegal_personInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_type_id?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  natural_person?: Prisma.NaturalPersonDetailUncheckedUpdateOneWithoutUserNestedInput
  users_roles?: Prisma.UserRoleUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutUsers_rolesInput = {
  id?: string
  user_type: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  document_type: Prisma.DocumentTypeCreateNestedOneWithoutUsersInput
  natural_person?: Prisma.NaturalPersonDetailCreateNestedOneWithoutUserInput
  legal_person?: Prisma.LegalPersonDetailCreateNestedOneWithoutUserInput
}

export type UserUncheckedCreateWithoutUsers_rolesInput = {
  id?: string
  user_type: string
  document_type_id: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  natural_person?: Prisma.NaturalPersonDetailUncheckedCreateNestedOneWithoutUserInput
  legal_person?: Prisma.LegalPersonDetailUncheckedCreateNestedOneWithoutUserInput
}

export type UserCreateOrConnectWithoutUsers_rolesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutUsers_rolesInput, Prisma.UserUncheckedCreateWithoutUsers_rolesInput>
}

export type UserUpsertWithoutUsers_rolesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutUsers_rolesInput, Prisma.UserUncheckedUpdateWithoutUsers_rolesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutUsers_rolesInput, Prisma.UserUncheckedCreateWithoutUsers_rolesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutUsers_rolesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutUsers_rolesInput, Prisma.UserUncheckedUpdateWithoutUsers_rolesInput>
}

export type UserUpdateWithoutUsers_rolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  document_type?: Prisma.DocumentTypeUpdateOneRequiredWithoutUsersNestedInput
  natural_person?: Prisma.NaturalPersonDetailUpdateOneWithoutUserNestedInput
  legal_person?: Prisma.LegalPersonDetailUpdateOneWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutUsers_rolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_type_id?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  natural_person?: Prisma.NaturalPersonDetailUncheckedUpdateOneWithoutUserNestedInput
  legal_person?: Prisma.LegalPersonDetailUncheckedUpdateOneWithoutUserNestedInput
}

export type UserCreateManyDocument_typeInput = {
  id?: string
  user_type: string
  document_number: string
  mail: string
  hashed_password: string
  phone_number: string
  is_active?: boolean
  registration_date?: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
}

export type UserUpdateWithoutDocument_typeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  natural_person?: Prisma.NaturalPersonDetailUpdateOneWithoutUserNestedInput
  legal_person?: Prisma.LegalPersonDetailUpdateOneWithoutUserNestedInput
  users_roles?: Prisma.UserRoleUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutDocument_typeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  natural_person?: Prisma.NaturalPersonDetailUncheckedUpdateOneWithoutUserNestedInput
  legal_person?: Prisma.LegalPersonDetailUncheckedUpdateOneWithoutUserNestedInput
  users_roles?: Prisma.UserRoleUncheckedUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateManyWithoutDocument_typeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  document_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  hashed_password?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registration_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  users_roles: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users_roles?: boolean | UserCountOutputTypeCountUsers_rolesArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountUsers_rolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserRoleWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_type?: boolean
  document_type_id?: boolean
  document_number?: boolean
  mail?: boolean
  hashed_password?: boolean
  phone_number?: boolean
  is_active?: boolean
  registration_date?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  document_type?: boolean | Prisma.DocumentTypeDefaultArgs<ExtArgs>
  natural_person?: boolean | Prisma.User$natural_personArgs<ExtArgs>
  legal_person?: boolean | Prisma.User$legal_personArgs<ExtArgs>
  users_roles?: boolean | Prisma.User$users_rolesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_type?: boolean
  document_type_id?: boolean
  document_number?: boolean
  mail?: boolean
  hashed_password?: boolean
  phone_number?: boolean
  is_active?: boolean
  registration_date?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  document_type?: boolean | Prisma.DocumentTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_type?: boolean
  document_type_id?: boolean
  document_number?: boolean
  mail?: boolean
  hashed_password?: boolean
  phone_number?: boolean
  is_active?: boolean
  registration_date?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  document_type?: boolean | Prisma.DocumentTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  user_type?: boolean
  document_type_id?: boolean
  document_number?: boolean
  mail?: boolean
  hashed_password?: boolean
  phone_number?: boolean
  is_active?: boolean
  registration_date?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_type" | "document_type_id" | "document_number" | "mail" | "hashed_password" | "phone_number" | "is_active" | "registration_date" | "created_at" | "updated_at" | "deleted_at", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  document_type?: boolean | Prisma.DocumentTypeDefaultArgs<ExtArgs>
  natural_person?: boolean | Prisma.User$natural_personArgs<ExtArgs>
  legal_person?: boolean | Prisma.User$legal_personArgs<ExtArgs>
  users_roles?: boolean | Prisma.User$users_rolesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  document_type?: boolean | Prisma.DocumentTypeDefaultArgs<ExtArgs>
}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  document_type?: boolean | Prisma.DocumentTypeDefaultArgs<ExtArgs>
}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    document_type: Prisma.$DocumentTypePayload<ExtArgs>
    natural_person: Prisma.$NaturalPersonDetailPayload<ExtArgs> | null
    legal_person: Prisma.$LegalPersonDetailPayload<ExtArgs> | null
    users_roles: Prisma.$UserRolePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_type: string
    document_type_id: string
    document_number: string
    mail: string
    hashed_password: string
    phone_number: string
    is_active: boolean
    registration_date: Date
    created_at: Date
    updated_at: Date
    deleted_at: Date | null
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  document_type<T extends Prisma.DocumentTypeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentTypeDefaultArgs<ExtArgs>>): Prisma.Prisma__DocumentTypeClient<runtime.Types.Result.GetResult<Prisma.$DocumentTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  natural_person<T extends Prisma.User$natural_personArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$natural_personArgs<ExtArgs>>): Prisma.Prisma__NaturalPersonDetailClient<runtime.Types.Result.GetResult<Prisma.$NaturalPersonDetailPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  legal_person<T extends Prisma.User$legal_personArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$legal_personArgs<ExtArgs>>): Prisma.Prisma__LegalPersonDetailClient<runtime.Types.Result.GetResult<Prisma.$LegalPersonDetailPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users_roles<T extends Prisma.User$users_rolesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$users_rolesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly user_type: Prisma.FieldRef<"User", 'String'>
  readonly document_type_id: Prisma.FieldRef<"User", 'String'>
  readonly document_number: Prisma.FieldRef<"User", 'String'>
  readonly mail: Prisma.FieldRef<"User", 'String'>
  readonly hashed_password: Prisma.FieldRef<"User", 'String'>
  readonly phone_number: Prisma.FieldRef<"User", 'String'>
  readonly is_active: Prisma.FieldRef<"User", 'Boolean'>
  readonly registration_date: Prisma.FieldRef<"User", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"User", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"User", 'DateTime'>
  readonly deleted_at: Prisma.FieldRef<"User", 'DateTime'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.natural_person
 */
export type User$natural_personArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NaturalPersonDetail
   */
  select?: Prisma.NaturalPersonDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NaturalPersonDetail
   */
  omit?: Prisma.NaturalPersonDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturalPersonDetailInclude<ExtArgs> | null
  where?: Prisma.NaturalPersonDetailWhereInput
}

/**
 * User.legal_person
 */
export type User$legal_personArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalPersonDetail
   */
  select?: Prisma.LegalPersonDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalPersonDetail
   */
  omit?: Prisma.LegalPersonDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalPersonDetailInclude<ExtArgs> | null
  where?: Prisma.LegalPersonDetailWhereInput
}

/**
 * User.users_roles
 */
export type User$users_rolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  where?: Prisma.UserRoleWhereInput
  orderBy?: Prisma.UserRoleOrderByWithRelationInput | Prisma.UserRoleOrderByWithRelationInput[]
  cursor?: Prisma.UserRoleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserRoleScalarFieldEnum | Prisma.UserRoleScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
